### ISSUE TITLE
vCloud Air Acquisition by OVH Possible Development Impact?

### ISSUE THREAD

**Issue by montj2** [vmware/pyvcloud#102]
Will the recent vCloud Air acquisition by OVH impact the development of pyvcloud?

**Comment by pacogomez** [comment]
@montj2 I'm planning to keep developing and maintaining pyvcloud and vca-cli

**Comment by hodgesrm** [comment]
Pyvcloud is under active development by the vCD engineering team and the user community.  Note that we've move the project to Python3, have added new features since this was logged, and support schema versions up to vCD 9.1.  

Please join the community and help us improve pyvcloud!
