### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ruslantum** [vmware/pyvcloud#108]
https://github.com/vmware/pyvcloud/blob/eaa614498bb8eef1f98f1c81f7e66fc040c56c1d/pyvcloud/vapp.py#L940

I am using pyvcloud Library in my Ansible dynamic inventory script. After upgrading to the newest version of pyvloud it started failing with the following traceback:
```
ERROR! Attempted to execute 
...
line 176, in update_cache
    vms_details = the_vapp.get_vms_details()
  File "/home/tumarkin/.virtualenvs/ansible2-stable/lib/python2.7/site-packages/pyvcloud/vapp.py", line 940, in get_vms_details
    property_section = filter(lambda section: section.__class__.__name__ == 'PropertySection_Type', es)[0]
IndexError: list index out of range
```

Possible solution:
enclose the property section with ``try ... except IndexError: pass``

**Comment by pacogomez** [comment]
the latest version should include this fix:

pyvcloud-18.0.4.dev36
