### ISSUE TITLE
Misleading Test/Documentation or Feature Request

### ISSUE THREAD

**Issue by cpumanaz** [vmware/pyvcloud#109]
Test 0024 in (vcloud_tests.py line 619) seems to indicate that you can  and pass cpus and memory as arguments when testing compose_vapp().

        vm_specs = [{
            'template': template,
            'catalog': catalog,
            'name': vm_name,
            'cpus': 3,
            'memory': 4096,
            'storage_profile': storage_profile
        }]

compose_vapp() however does not take either of those two items from the dictionary and put them into the params object.

Can the documentation be updated, an example provided on how to do this if supported, or ideally the compose_vapp updated to allow setting the cpu and memory if it is not. I'm hopeful as this project is under active development, and it would make sense to complete the provisioning of the target VM at the time the vApp is created to avoid additional coding, or taking additional time/cycles of the vCloud.

Bonus if there is an option to set a customization script at this phase, no worries as I'm going to force configuration and power on afterwards.

Thanks, 

-Matt

**Comment by kkkothari** [comment]
I am not able to find the file vcloud_tests.py.
