### ISSUE TITLE
can't login if the SSL certificate is self signed

### ISSUE THREAD

**Issue by tonton1728** [vmware/pyvcloud#11]
My VCloud Director works with a self signed SSL certificate.
When I try to log on, I got this error

/usr/lib/python2.6/site-packages/pyvcloud-0.8-py2.6.egg/pyvcloud/vcloudair.pyc in login(self, host, username, password, token, service_type, version)
     71                 headers["Authorization"] = encode.rstrip()
     72                 headers["Accept"] = "application/xml;version=" + version
---> 73                 response = requests.post(url, headers=headers)
     74                 if response.status_code == requests.codes.created:
     75                     self.host = host

/usr/lib/python2.6/site-packages/requests-2.4.3-py2.6.egg/requests/api.pyc in post(url, data, json, **kwargs)
     92     """
     93
---> 94     return request('post', url, data=data, json=json, **kwargs)
     95
     96

/usr/lib/python2.6/site-packages/requests-2.4.3-py2.6.egg/requests/api.pyc in request(method, url, **kwargs)
     47
     48     session = sessions.Session()
---> 49     return session.request(method=method, url=url, **kwargs)
     50
     51

/usr/lib/python2.6/site-packages/requests-2.4.3-py2.6.egg/requests/sessions.pyc in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    455         }
    456         send_kwargs.update(settings)
--> 457         resp = self.send(prep, **send_kwargs)
    458
    459         return resp

/usr/lib/python2.6/site-packages/requests-2.4.3-py2.6.egg/requests/sessions.pyc in send(self, request, **kwargs)
    567
    568         # Send the request
--> 569         r = adapter.send(request, **kwargs)
    570
    571         # Total elapsed time of the request (approximately)

/usr/lib/python2.6/site-packages/requests-2.4.3-py2.6.egg/requests/adapters.pyc in send(self, request, stream, timeout, verify, cert, proxies)
    418         except (_SSLError, _HTTPError) as e:
    419             if isinstance(e, _SSLError):
--> 420                 raise SSLError(e, request=request)
    421             elif isinstance(e, ReadTimeoutError):
    422                 raise ReadTimeout(e, request=request)

Is there a way to force the script not to check the Certificate validity ?

Thanks for your answer

**Comment by pacogomez** [comment]
you can now use the param 'verify=False' in the VCA object to use self signed SSL certificates
