### ISSUE TITLE
VDC resources not filtered by EntityType

### ISSUE THREAD

**Issue by Foley** [vmware/pyvcloud#115]
The EntityType parameter is not being used in the get_resource_href method so this is not filtering resources as expected.
https://github.com/vmware/pyvcloud/blob/8a8767cb314237fbf2b16d9d85efd9c2bc2787dd/pyvcloud/vcd/vdc.py#L41

The get_vapp method is returning vApps and vApp Templates because of this. It looks like this can be resolved by using the EntityType to filter the resources like the list_resources method:
https://github.com/vmware/pyvcloud/blob/8a8767cb314237fbf2b16d9d85efd9c2bc2787dd/pyvcloud/vcd/vdc.py#L245

**Comment by pacogomez** [comment]
@Foley, Thanks. I will be fixing this issue.
