### ISSUE TITLE
Upload OVF to a catalog

### ISSUE THREAD

**Issue by akulkarni-rvbd** [vmware/pyvcloud#14]
Is it possible to upload OVF to a catalog? In the VCA class I only method to create a catalog and delete a catalog. How do I upload an OVF to a catalog ?

Thanks

**Comment by pacogomez** [comment]
we might add this feature in the future. in the meantime, you can use ovftool as described here: http://blog.pacogomez.com/coreos-vcloud-air-on-demand/
