### ISSUE TITLE
vdc.get_storage_profiles only return the first element

### ISSUE THREAD

**Issue by pylanglois** [vmware/pyvcloud#142]
https://github.com/vmware/pyvcloud/blob/a3e991fdbd806d23fe8f385d07d362c68ae5eeb6/pyvcloud/vcd/vdc.py#L549

This line returns only the first storage profile. Maybe remove this line and return profile_list and the end instead of None

**Comment by rocknes** [comment]
Fixed via https://github.com/vmware/pyvcloud/commit/ceb48a3266483f1959cc715aa737e20f6872111b
