### ISSUE TITLE
Create multiple vapp networks

### ISSUE THREAD

**Issue by ihafiri** [vmware/pyvcloud#198]
Which method can be used to create additional vapp networks? specifically the type of virtual networks mentioned in 
https://pubs.vmware.com/vcd-820/index.jsp#com.vmware.vcloud.user.doc/GUID-9F68D2D9-016F-49AF-973E-12B723473C07.html

I was looking at tests/vcd_vapp.py line 46, I couldn't find where this function is implemented vdc.reconfigure_vapp_network()

**Comment by hodgesrm** [comment]
Have a look at vdc.create_isolated_vdc_network in https://github.com/vmware/pyvcloud/blob/master/pyvcloud/vcd/vdc.py.  You can see an example of usage in https://github.com/vmware/vcd-cli/blob/master/vcd_cli/network.py (look at create_isolated_network). 

You don't mention which version of pyvcloud you are using.  This is from the most current dev version.  You can get it using the instructions in docs/install.md.  Enjoy!

Cheers, Robert

**Comment by hodgesrm** [comment]
Hi again, 

My apologies--I believe I misread your question.  My answer applies to VDC isolated networks.  If you are looking for *vapp* networks pyvcloud does not have this yet. 

Cheers, Robert
