### ISSUE TITLE
Use with vCloudDirector API ?

### ISSUE THREAD

**Issue by nlamirault** [vmware/pyvcloud#2]
hi,
it is possible to use this API to authenticate and use the vCloud Director API ?
Thanks.

**Comment by pacogomez** [comment]
yes, it is possible in 0.3

here is an example:
vca = VCA()
vca.login('https://vclouddirectorhost.domain.com', 'username@organization', 'password', None, 'vcd', '5.6)
vcd = vca.get_vCloudDirector()
vapps = vcd.get_vApps()

**Comment by nlamirault** [comment]
Great ! Thanks
