### ISSUE TITLE
Unable to create a new VM with a different target_vm_name

### ISSUE THREAD

**Issue by ihafiri** [vmware/pyvcloud#207]
adding new virtual machines to an existing vApp using vapp.add_vms([specs]) results in the following error:

pyvcloud.vcd.client.VcdErrorResponseException: Status code: 400/BAD_REQUEST, Bad request  - Unexpected JAXB Exception  - cvc-complex-type.2.4.a: Invalid content was found starting with element 'VmGeneralParams'

removing the VmGeneralParams from sourced item, the request runs fine and the VM is created successfully. However, I lose the ability to create a VM with a different target_vm_name

API versions: 1.5 and 5.5

**Comment by ihafiri** [comment]
To add to the above: It would be useful to have a way to rename an existing virtual machine.
Thanks

**Comment by pandeys** [comment]
API version 1.5 and 5.5 are not supported. If you are facing issue in API>=29.0, please reopen the issue.
