### ISSUE TITLE
cannot import name Http

### ISSUE THREAD

**Issue by Bareliah** [vmware/pyvcloud#208]
installing pyvcloud and get an error:
    from pyvcloud import  Http, Log
ImportError: cannot import name Http

looks like all the requirements are satisfied:
user@localhost:~/files$ pip install pyvcloud -v
Requirement already satisfied: pyvcloud in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: lxml>=3.4.1 in /home/osmuser/.local/lib/python2.7/site-packages (from pyvcloud)
Requirement already satisfied: pygments>=2.2.0 in /usr/local/lib/python2.7/dist-packages (from pyvcloud)
Requirement already satisfied: requests>=2.18.4 in /home/osmuser/.local/lib/python2.7/site-packages (from pyvcloud)
Requirement already satisfied: flufl.enum>=4.1.1 in /usr/local/lib/python2.7/dist-packages (from pyvcloud)
Requirement already satisfied: humanfriendly>=4.8 in /usr/local/lib/python2.7/dist-packages (from pyvcloud)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python2.7/dist-packages (from pyvcloud)
Requirement already satisfied: certifi>=2017.4.17 in /home/osmuser/.local/lib/python2.7/site-packages (from requests>=2.18.4->pyvcloud)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/osmuser/.local/lib/python2.7/site-packages (from requests>=2.18.4->pyvcloud)
Requirement already satisfied: idna<2.7,>=2.5 in /home/osmuser/.local/lib/python2.7/site-packages (from requests>=2.18.4->pyvcloud)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/osmuser/.local/lib/python2.7/site-packages (from requests>=2.18.4->pyvcloud)
Requirement already satisfied: monotonic; python_version == "2.6" or python_version == "2.7" or python_version == "3.0" or python_version == "3.1" or python_version == "3.2" in /usr/local/lib/python2.7/dist-packages (from humanfriendly>=4.8->pyvcloud)
Cleaning up...
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 200 72983

any idea?

-------------------------------------------------------

Update : I downgrade pyvcloud from pyvcloud==19.1.1 to pyvcloud==18.2.1 and it works.
I think there is a bug with 19.1.1 version or this module design changed and it's not backward compatibility for purpose?

**Comment by hodgesrm** [comment]
Hi!

Can you show the command(s) you executed to get this error?  Assuming it's happening during setup, please provide your OS and Python version and the output of 'pip3 freeze'.  Thanks!

Robert

**Comment by Bareliah** [comment]
Hi Robert.

during setup, it looks pyvcloud installed successfully.
for a test I just created an empty file which looks like this:
```
#!/usr/bin/env python
from pyvcloud import  Http, Log

```
Python version: 

> Python 2.7.12 (default, Dec  4 2017, 14:50:18)

pip freeze

> adium-theme-ubuntu==0.3.4
> ansible==2.0.0.2
> certifi==2018.1.18
> chardet==3.0.4
> click==6.2
> colorama==0.3.7
> configparser==3.5.0
> docopt==0.6.2
> ecdsa==0.13
> enum34==1.1.6
> flake8==2.5.5
> flake8-docstrings==1.3.0
> flake8-import-order==0.17
> flake8-polyfill==1.0.2
> flufl.enum==4.1.1
> hacking==1.0.0
> http==0.2
> httplib2==0.9.1
> humanfriendly==4.8
> idna==2.6
> Jinja2==2.8
> lxml==4.1.1
> MarkupSafe==0.23
> mccabe==0.2.1
> monotonic==1.4
> netaddr==0.7.18
> osmclient==3.0.1.post4
> paramiko==1.16.0
> pbr==3.1.1
> pep8==1.5.7
> pluggy==0.6.0
> prettytable==0.7.2
> prompt-toolkit==1.0.15
> py==1.5.2
> pycodestyle==2.3.1
> pycrypto==2.6.1
> pycurl==7.43.0
> pydocstyle==2.1.1
> pyflakes==0.8.1
> Pygments==2.2.0
> pyvcloud==19.1.1
> pyvim==0.0.21
> pyvmomi==6.5.0.2017.5.post1
> PyYAML==3.12
> requests==2.18.4
> six==1.11.0
> snowballstemmer==1.2.1
> tox==2.9.1
> unity-lens-photos==1.0
> urllib3==1.22
> virtualenv==15.1.0
> wcwidth==0.1.7
> yapf==0.20.2
> yolk==0.4.3
> The directory '/home/osmuser/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> osmuser@osmv302:~/.allot/roles/create_sgve200_answer_files/files$ sudo !!
> sudo pip freeze
> [sudo] password for osmuser:
> adium-theme-ubuntu==0.3.4
> ansible==2.0.0.2
> certifi==2018.1.18
> chardet==3.0.4
> click==6.2
> colorama==0.3.7
> configparser==3.5.0
> docopt==0.6.2
> ecdsa==0.13
> enum34==1.1.6
> flake8==2.5.5
> flake8-docstrings==1.3.0
> flake8-import-order==0.17
> flake8-polyfill==1.0.2
> flufl.enum==4.1.1
> hacking==1.0.0
> http==0.2
> httplib2==0.9.1
> humanfriendly==4.8
> idna==2.6
> Jinja2==2.8
> lxml==4.1.1
> MarkupSafe==0.23
> mccabe==0.2.1
> monotonic==1.4
> netaddr==0.7.18
> osmclient==3.0.1.post4
> paramiko==1.16.0
> pbr==3.1.1
> pep8==1.5.7
> pluggy==0.6.0
> prettytable==0.7.2
> prompt-toolkit==1.0.15
> py==1.5.2
> pycodestyle==2.3.1
> pycrypto==2.6.1
> pycurl==7.43.0
> pydocstyle==2.1.1
> pyflakes==0.8.1
> Pygments==2.2.0
> pyvcloud==19.1.1
> pyvim==0.0.21
> pyvmomi==6.5.0.2017.5.post1
> PyYAML==3.12
> requests==2.18.4
> six==1.11.0
> snowballstemmer==1.2.1
> tox==2.9.1
> unity-lens-photos==1.0
> urllib3==1.22
> virtualenv==15.1.0
> wcwidth==0.1.7
> yapf==0.20.2
> yolk==0.4.3

Thank you!
Bar.

**Comment by Bareliah** [comment]
UPDATE: comparing between two ubuntu16.04 hosts, one host has pyvcloud for months and the second one just installed yesterday.
_old_ host:
~$ python
```
Python 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvcloud
>>> print pyvcloud.__dict__.keys()
['httplib', 'logging', 'Log', 'tempfile', '__builtins__', '__file__', 'Http', '__package__', '_logger', '__path__', '_get_logger', '__name__', 'requests', '__doc__']
```
_new_ host:
```
~$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvcloud
>>> print pyvcloud.__dict__.keys()
['__builtins__', '__file__', '__package__', '__path__', '__name__', '__doc__']
```

**Comment by hodgesrm** [comment]
Thanks for the additional information!  To answer your question, older versions of pyvcloud defined an Http and a Log class in pyvcloud/__init__.py.  That's why you were able to import them. We removed these as part of exposing a clean API layer focused on vCD operations.  They are no longer part of pyvcloud.   You can see the history of the changes in git using the following command: 

   git log -p pyvcloud/__init__.py

If your applications needs the functions from these classes for its own use, you should be able to get them by importing logger and request normally.  If you are extending pyvcloud itself, have a look in client.py for current usage.  

Cheers, Robert

**Comment by hodgesrm** [comment]
p.s., Pyvcloud no longer officially supports Python 2. Please move to Python3--it's not possible to guarantee pyvcloud will even function correctly on Python 2.x versions.
