### ISSUE TITLE
Add vm to existing vapp

### ISSUE THREAD

**Issue by akulkarni-rvbd** [vmware/pyvcloud#21]
How do I add vm to an already existing vapp?

**Comment by akulkarni-rvbd** [comment]
Any example on adding vms to existing vapps

**Comment by denismakogon** [comment]
@akulkarni-rvbd this is not an issue, please contact core team for more info and close this ticket please.

**Comment by xcompass** [comment]
Any info on this? I'm wondering too.

**Comment by rvdh** [comment]
@denismakogon Could you please elaborate on the "not an issue" statement? I need to add a vm to an existing vApp aswell and this currently seems impossible.

**Comment by sanderv32** [comment]
Same for me. I can't create a new VM into an existing vApp with the current supplied functions.

**Comment by kkkothari** [comment]
try add_vms(self, specs,  deploy=True,  power_on=True, all_eulas_accepted=None,  source_delete=False) in vapp.py
