### ISSUE TITLE
Unable to delete an existing virtual machine when other VM in the same vapp can be accessed.

### ISSUE THREAD

**Issue by xudehua** [vmware/pyvcloud#212]
example:
There is three vms(name:A,B,C) in the vApp,I want to delete one(A) of vms using vapp.delete_vms(self, A).
when the status of vApp and vms(B,C) is "power on",the status vm(A) is "power off" and "undeploy",the function of   vapp.delete_vms(self, A) is failed.
when the status of vApp and vms(A,B,C) is "power off",the function of vapp.delete_vms(self, A) is successed.But vms(B,C) will not work.

Our purpose is scale-in an vapp， so we want to delete a vm while others vms in this vapp are still working，any methods could achied this goal？

**Comment by hodgesrm** [comment]
Hi @xudehua, 

Which version of pyvcloud are you using and can you provide a short code sample that shows the problem you are encountering?  This will make it easier for us to help you. (See https://github.com/vmware/pyvcloud/blob/master/CONTRIBUTING.md for tips on logging bugs.) 

Cheers, Robert

**Comment by xudehua** [comment]
Hi @hodgesrm
Thanks for your responses. 
Platform : Linux version 3.10.0-514.10.2.el7.x86_64 (mockbuild@x86-039.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) )
pyvcloud version : 19.0.0
steps to reproduce :
1 use 'vdc.instantiate_vapp' create a vApp, the vApp and vms are in 'deployed' status
2 use 'vm.undeploy()' , undeploy and power off a vm, the vApp status now auto change to 'Partially running'
3 use 'vapp.delete_vms(vm)' to delete a vm, and then failed. the exceptions as below:
Deleting the vm......
Traceback (most recent call last):
  File "./clcm", line 14, in <module>
    clcm()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/clcm/terraform/vcd/bin/commands/cluster/deploy.py", line 260, in scale_in
    result = vapp.delete_vms(vms)
  File "/clcm/terraform/vcd/pyvcloud/vcd/vapp.py", line 508, in delete_vms
    EntityType.RECOMPOSE_VAPP_PARAMS.value, params)
  File "/clcm/terraform/vcd/pyvcloud/vcd/client.py", line 835, in post_linked_resource
    find_link(resource, rel, media_type).href, contents, media_type)
  File "/clcm/terraform/vcd/pyvcloud/vcd/client.py", line 992, in find_link
    raise MissingLinkException(resource.get('href'), rel, media_type)
pyvcloud.vcd.client.MissingLinkException: ; href: https://*.*.*.*/api/vApp/vapp-c305a2ae-7272-4978-beed-6f21023e9d04, rel: RelationType.RECOMPOSE, mediaType: application/vnd.vmware.vcloud.recomposeVAppParams+xml

After some debug, I found that only all vms contained in this vApp are all in 'undeploy and poweroff' status, then I can delete the vm,
otherwise above exceptions will appear. 
Now my purpose is deleting a vm at same time keeping other vms are running , I found that it can not achieved when other vms are in running status
even I use 'vcd-cli' command.
So is there any methond or workaround can achieved this goal? or is it impossible?

Thanks for your help.

**Comment by sahithi** [comment]
Can you quickly try invoking direct GET rest-api call (via postman) to get the vApp in question? Scan the response body to see if it has the link "rel: recompose, mediaType: application/vnd.vmware.vcloud.recomposeVAppParams+xml"? 

Basically MissingLinkException occurs either when server denies the operation for any reason (lack of enough privileges (or) the entity is not in the right state)

**Comment by xudehua** [comment]
Hi @sahithi 
VMware, Inc.® VMware vCloud Director
Version:     8.10.0.3879706
Build date:  05/13/2016

user role Organization Administrator

when I have runned vapp.undeploy(),there is the link "rel: recompose, mediaType:application/vnd.vmware.vcloud.recomposeVAppParams+xml" in the response body.
The status of the Vapp is "Stopped" and the status value is 8.
After above operation, vms which contained in this vApp are all in "Powered Off" status. 

Any other operations can't find the link "rel: recompose, mediaType:application/vnd.vmware.vcloud.recomposeVAppParams+xml".
for example:
1.vapp.power_off() or vapp.shutdown()
  The status of the Vapp is "Partially Running" and the status value is 8.
2.vm.undeploy() and vapp.power_off()
  The status of the Vapp is "Partially Running" and the status value is 8 or 10.

Thank you

**Comment by xudehua** [comment]
Who can tell me?
when run vapp.delete_vms(name) function,what is the status of the vApp and the vms which contained in this vApp?
Other,According to above operation,it suessfully delete vm using java SDK.

**Comment by sahithi** [comment]
Hi Xudehua,

Thank you for the detailed clarification. This looks like a bug in pyvcloud. 
There are couple of ways to delete any particular VM. We can either invoke HTTP DELETE operation directly on the resource (or) we can invoke a HTTP PUT (recompose) operation on vApp to delete a Vm.

Apparently, recompose operation on vApp is not allowed when vApp is in certain states (when vApp is poweredoff or partially running). We will investigate further.

Possible fix here would be invoke a DELETE call directly on the VM instead of recompose operation on vApp. 

Thanks
Sahithi

**Comment by rocknes** [comment]
I just ran the following workflow using ToT of vcd-cli (which is using pyvcloud in the background)
1. Create a vApp with 2 vms (not connected to any networks)
2. Power on the vApp
3. Undeploy one of the vms
4. Check that hte vApp is in partially running state
5. Delete the powered off vm

(vcd-cli) C:\code\vcd-cli>vcd vapp info test_vapp
property                     value
---------------------------  ----------------------------------------
deployment_lease             12.857142857142858w, 0.0d, 0.0h
deployment_lease_expiration  2018-06-07T21:06:03.950-04:00
id                           a522bc3e-081b-4aee-a218-24bd7c55484c
is_shared_to_everyone        False
name                         test_vapp
owner                        sena
status                       Children do not all have the same status
storage_lease                4.285714285714286w, 0.0d, 0.0h
vapp-net-1                   none
vapp-net-1-mode              isolated
vm-1: 1 virtual CPU(s)       1
vm-1: 4 MB of memory         4
vm-1: CD/DVD Drive 1         CD/DVD Drive
vm-1: Floppy Drive 1         Floppy Drive
vm-1: Hard disk 1            41,943,040 byte
vm-1: IDE Controller 0       IDE Controller
vm-1: Network adapter 0      NONE: None
vm-1: SCSI Controller 0      SCSI Controller
vm-1: computer-name          vm2
vm-1: name                   vm2
vm-1: storage-profile        *
vm-2: 1 virtual CPU(s)       1
vm-2: 4 MB of memory         4
vm-2: CD/DVD Drive 1         CD/DVD Drive
vm-2: Floppy Drive 1         Floppy Drive
vm-2: Hard disk 1            41,943,040 byte
vm-2: IDE Controller 0       IDE Controller
vm-2: Network adapter 0      NONE: None
vm-2: SCSI Controller 0      SCSI Controller
vm-2: computer-name          vm1
vm-2: name                   vm1
vm-2: storage-profile        *

(vcd-cli) C:\code\vcd-cli>vcd vapp undeploy test_vapp vm1
Are you sure you want to undeploy the vApp or VM(s)? [y/N]: y
vappUndeployPowerOff: Stopping Virtual Machine vm1(cb9ab233-a784-46bf-9b45-d31a0bded571), status: runvappUndeployPowerOff: Stopping Virtual Machine vm1(cb9ab233-a784-46bf-9b45-d31a0bded571)
vappUndeployPowerOff: Stopped Virtual Machine vm1(cb9ab233-a784-46bf-9b45-d31a0bded571), status: succtask: 17de435e-7dfc-4002-a345-daba1b47da2b, Stopped Virtual Machine vm1(cb9ab233-a784-46bf-9b45-d31a0bded571), result: success

(vcd-cli) C:\code\vcd-cli>vcd vapp delete test_vapp vm1
Are you sure you want to delete the vApp or the VM(s)? [y/N]: y
vdcRecomposeVapp: Recomposed Virtual Application test_vapp(a522bc3e-081b-4aee-a218-24bd7c55484c), statask: a5d50991-5a9e-4c25-8b01-675b7deece6b, Recomposed Virtual Application test_vapp(a522bc3e-081b-4aee-a218-24bd7c55484c), result: success

(vcd-cli) C:\code\vcd-cli>vcd vapp info test_vapp
property                     value
---------------------------  ------------------------------------
deployment_lease             12.857142857142858w, 0.0d, 0.0h
deployment_lease_expiration  2018-06-07T21:08:02.943-04:00
id                           a522bc3e-081b-4aee-a218-24bd7c55484c
is_shared_to_everyone        False
name                         test_vapp
owner                        sena
status                       Powered on
storage_lease                4.285714285714286w, 0.0d, 0.0h
vapp-net-1                   none
vapp-net-1-mode              isolated
vm-1: 1 virtual CPU(s)       1
vm-1: 4 MB of memory         4
vm-1: CD/DVD Drive 1         CD/DVD Drive
vm-1: Floppy Drive 1         Floppy Drive
vm-1: Hard disk 1            41,943,040 byte
vm-1: IDE Controller 0       IDE Controller
vm-1: Network adapter 0      NONE: None
vm-1: SCSI Controller 0      SCSI Controller
vm-1: computer-name          vm2
vm-1: name                   vm2
vm-1: storage-profile        *

(vcd-cli) C:\code\vcd-cli>

I didn't see any error in the workflow.

**Comment by rocknes** [comment]
I will like to highlight one thing regarding vCD 8.10 though. There were few issues around vApp power-on/off and general power status, which were fixed recently in 9.0. It's highly likely that the issue you are seeing is not a pyvcloud/vcd-cli issue but an error in vCD 8.10 itself.

**Comment by rocknes** [comment]
Also, wanted to mention that as per vCD ReST API docs, there is no valid DELETE operation on vms.

The only way to delete vm(s) in vCD is to call a POST /vApp/{id}/action/recomposeVApp on the target vApp with a corresponding vAppRecomposeParams payload (which has a DeleteItem section). 

The current implementation of pyvcloud uses the above mentioned _correct_ method to delete a vm.

**Comment by xudehua** [comment]
Thank you for you help! I'm going to find a vCD 9.1 to test it.
Now I can invoke HTTP DELETE operation directly on the VM to delete VM.

def delete_vm_xml(self, vapp, item_name):
    vm = vapp.get_vm(item_name)

    headers = {'Accept': 'application/*;version={}'.format(self._api_version),
               'x-vcloud-authorization': '{}'.format(self._session.headers['x-vcloud-authorization']),
               'Content-Type': 'application/vnd.vmware.vcloud.task+xml'}
    response = requests.delete(vm.get('href'), headers=headers, verify=False)
    sc = response.status_code
    if sc != 202:
        raise Exception('Unable to delete this vm {}.'.format(vm.get('href')))
        return -1
    else:
        return 0

Other,I meet the same problem that the vApp must be poweeed off, when called vapp.vms(vms) function.
I used two methods.
First,invoking a HTTP PUT (recompose) operation on vApp to delete a Vm.

def add_vms_xml(self, vapp_link, template_link):

    headers = {'Accept': 'application/*;version={}'.format(self._api_version),
               'x-vcloud-authorization': '{}'.format(self._session.headers['x-vcloud-authorization']),
               'Content-Type': 'application/vnd.vmware.vcloud.recomposeVAppParams+xml'}
    xml = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                    <RecomposeVAppParams
                    xmlns="http://www.vmware.com/vcloud/v1.5"
                    xmlns:ns2="http://schemas.dmtf.org/ovf/envelope/1"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1"
                    xmlns:environment_1="http://schemas.dmtf.org/ovf/environment/1">
                    <Description> "api deployed vm to ol-vapp-04" </Description>
                        <SourcedItem sourceDelete="false">
                            <Source href="%s"/>
                        </SourcedItem>
                    <AllEULAsAccepted>true</AllEULAsAccepted>
                    </RecomposeVAppParams>""" % (template_link)

    post = requests.post(vapp_link + '/action/recomposeVApp', data=xml, headers=headers)
    result = ET.fromstring(post.text)

But it display "requests.exceptions.SSLError: HTTPSConnectionPool(host='*.*.*.*', port=4 f2-bc86-763b3524fbea/action/recomposeVApp (Caused by SSLError(SSLError(1, u'[SSL'),))".
I think it may be the question of the parameter 'xml'.

can you provide a 'xml' template?

Another method which adding vm to a running vapp is :
1 first , I create vapp contained vm which I want to add.
2 I use api to copy or move this vm to my target vapp
    PS: I try that add_vms sdk call , but it works only when target vapp is power off
3 I delete the vapp I created in step 1
the question is if this method works, if works which api I could use, if there is an example I would appreciated.

**Comment by xudehua** [comment]
Thank you for you help! I'm going to find a vCD 9.1 to test it.
Now I can invoke HTTP DELETE operation directly on the VM to delete VM.

def delete_vm_xml(self, vapp, item_name):
    vm = vapp.get_vm(item_name)

    headers = {'Accept': 'application/*;version={}'.format(self._api_version),
               'x-vcloud-authorization': '{}'.format(self._session.headers['x-vcloud-authorization']),
               'Content-Type': 'application/vnd.vmware.vcloud.task+xml'}
    response = requests.delete(vm.get('href'), headers=headers, verify=False)
    sc = response.status_code
    if sc != 202:
        raise Exception('Unable to delete this vm {}.'.format(vm.get('href')))
        return -1
    else:
        return 0

Other,I meet the same problem that the vApp must be poweeed off, when called vapp.vms(vms) function.
I used two methods.
First,invoking a HTTP PUT (recompose) operation on vApp to delete a Vm.

def add_vms_xml(self, vapp_link, template_link):

    headers = {'Accept': 'application/*;version={}'.format(self._api_version),
               'x-vcloud-authorization': '{}'.format(self._session.headers['x-vcloud-authorization']),
               'Content-Type': 'application/vnd.vmware.vcloud.recomposeVAppParams+xml'}
    xml = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                    <RecomposeVAppParams
                    xmlns="http://www.vmware.com/vcloud/v1.5"
                    xmlns:ns2="http://schemas.dmtf.org/ovf/envelope/1"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1"
                    xmlns:environment_1="http://schemas.dmtf.org/ovf/environment/1">
                    <Description> "api deployed vm to ol-vapp-04" </Description>
                        <SourcedItem sourceDelete="false">
                            <Source href="%s"/>
                        </SourcedItem>
                    <AllEULAsAccepted>true</AllEULAsAccepted>
                    </RecomposeVAppParams>""" % (template_link)

    post = requests.post(vapp_link + '/action/recomposeVApp', data=xml, headers=headers, verify=False)
    result = ET.fromstring(post.text)

The program ran no error,but the new vm display 'Failed to Create' status on web brower. 
Activity Task Detail:
[ 96801c6d-298e-4c02-8afd-0c255479910f ] The operation failed because no suitable resource was found. Could not find a suitable datastore in hub "moref://32689a19-4af5-41f0-bf68-31df5895b364/ResourcePool#resgroup-8"; cause(s): There is no usable datastore.
No available datastores or datastore clusters.
 - PlacementException NO_FEASIBLE_PLACEMENT_SOLUTION

can you help me?

Another method which adding vm to a running vapp is :
1 first , I create vapp contained vm which I want to add.
2 I use api to copy or move this vm to my target vapp
    PS: I try that add_vms sdk call , but it works only when target vapp is power off
3 I delete the vapp I created in step 1
the question is if this method works, if works which api I could use, if there is an example I would appreciated.
