### ISSUE TITLE
Version 18.2.2 broken against VCD 9.0

### ISSUE THREAD

**Issue by rvdh** [vmware/pyvcloud#219]
We were getting errors using version 18.2.2 of the tools against our environment when trying to modify the memory of a virtual machine:

```Exception: (400, '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n<Error xmlns="http://www.vmware.com/vcloud/v1.5" xmlns:vmext="http://www.vmware.com/vcloud/extension/v1.5" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData" xmlns:common="http://schemas.dmtf.org/wbem/wscim/1/common" xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" xmlns:vmw="http://www.vmware.com/schema/ovf" xmlns:ovfenv="http://schemas.dmtf.org/ovf/environment/1" xmlns:ns9="http://www.vmware.com/vcloud/networkservice/1.0" xmlns:ns10="http://www.vmware.com/vcloud/networkservice/common/1.0" xmlns:ns11="http://www.vmware.com/vcloud/networkservice/ipam/1.0" xmlns:ns12="http://www.vmware.com/vcloud/versions" majorErrorCode="400" message="[ a35f3a10-e3bb-44e8-85cf-621114290d90 ] HTTP 400 Bad Request&#xA; - Undeclared namespace prefix &quot;xsi&quot; (for attribute &quot;nil&quot;)&#xA; at [row,col {unknown-source}]: [2,80]" minorErrorCode="BAD_REQUEST"/>\n')```

So I've added the xsi to the namespace declaration. After this, other errors occurred so I forked the tag 18.2.2 and began fixing the issues. The fork is here: https://github.com/avisi/pyvcloud/tree/fix_v18 but I'm not able to create a pull request for it. Is it possible that you create a v18 branch so I can submit a pull request?

The fixes are in https://github.com/avisi/pyvcloud/commit/e44ea2ea8f03d079acea7427e17e9e8464d8c3b6.

**Comment by goelaashima** [comment]
Thank you for reporting this. 

Can you try with the latest version, in fact?

**Comment by rvdh** [comment]
@goelaashima What latest version do you mean? pyvcloud 19? That's all python3 and my tool isn't ready for that (yet).

**Comment by goelaashima** [comment]
Hello rvdh

Version 18.2.2 is deprecated code base, which is no longer being maintained.

Please see https://github.com/vmware/pyvcloud -> Notes section.

Our recommendation here would be to move to the latest pyvcloud code base. Thanks.
Aashima

**Comment by hodgesrm** [comment]
As @goelaashima indicated pyvcloud has moved to Python3 and no longer supports Python2.  Following up on her recommendation I would recommend you use the forked codebase with your fixes but plan to upgrade to Python3 as soon as practical.  We look forward to seeing you on the new code.
