### ISSUE TITLE
Edge submodule on a roadmap?

### ISSUE THREAD

**Issue by germanium-git** [vmware/pyvcloud#228]
This question is more about the feature which will be supported in the future rather than fixing an issue.
The old version of pyvcloud's documentation https://pyvcloud.readthedocs.io/en/latest/ refers to the GitHub repository http://github.com/vmware/pyvcloud. But this GitHub repository refers to different documentation https://vmware.github.io/pyvcloud "Python SDK for VMware vCloud Director".

I’m a bit confused with what features already are deprecated and what features may be expected in future.

In the “old”  version of the pyvcloud, there was the pyvcloud.gateway module which no longer exists in the new one.
May I ask if there're plans to develop a submodule for managing edges? And if no plans for edge submodule then if at least the routed org networks are on a roadmap? The creation of routed Org networks was supported in the old release as opposed to the new pyvcloud.vcd.vdc module supporting only isolated networks now by utilizing  create_isolated_vdc_network feature.
Is there a workaround to get a routed org nw created?

Thank you,
Petr.

**Comment by hodgesrm** [comment]
Hi @germanium-git, 

The https://pyvcloud.readthedocs.io/en/latest/ page is obsolete.   We need to have a look a how to remove it or at least tag the pages so there is no confusion.  We now post documentation on https://vmware.github.io/pyvcloud/, which is a convention for all vmware Github projects. 

As to the roadmap, great question.  I'm planning on writing a blog article to cover this but here's the state of things in a nutshell.  Our internal roadmap is coordinated with vCloud Director releases to ensure that the SDK stays up-to-date with new vCD API versions.  The wallet-sized version looks like the following. 

vCD 9.0 (DONE) -- Upgrade to Python 3 (no more Python 2), cover functions for tenant-onboarding, add auth management APIs.

vCD 9.1 (IN PROGRESS) -- Easy-to-run tests (backed by an in-house build so we can keep everyone's code clean), improve pyvcloud exception handling.  

Post vCD 9.1 (FUTURE) -- Networking. Support for all network types, edge routers, and advanced networking on the list.  

We hope the community will jump in as and when they see interesting work.  If community members want to go after some of the networking features that will dovetail with our build/test work to enable us to accept pull requests very efficiently. 

Cheers, Robert

**Comment by mgaruccio** [comment]
Is there a new ETA on networking support in the module?

**Comment by MichalTaratuta** [comment]
Same here any idea on the ETA?

In the mean time:
Is it actually possible to create an edge gateway through the API? I could not find any reference for it other then list edge gateway?

**Comment by mgaruccio** [comment]
It looks like for whatever reason edge gateway and network creation is listed as an admin operation rather than a user one, check out https://code.vmware.com/apis/287/vcloud#/doc/doc/landing-admin_operations.html for the admin API reference.  haven't done any testing to see if a system-level account is needed to use those or if a tenant can create/change their own networks.

**Comment by germanium-git** [comment]
To my knowledge, the so-called Organization VDC Networks can be created by tenants regardless of being connected to an existing Edge gateway or not (I'm referring to Routed and Isolated networks). The right for the creation of Edge gateways is granted only to system administrators and Edges can't be created by tenants.

The documentation for creating Edge gateways is for some reason not covered by the recent API versions (etc. 27, 30, 31) but you can find it in the older API 9.0, page 199
[https://pubs.vmware.com/vcd-80/topic/com.vmware.ICbase/PDF/vcloud_sp_api_guide_90.pdf](url)

And it still works with 31.0, I've just tested with the Postman.
![createedge_headers_api31 0](https://user-images.githubusercontent.com/31744880/48849886-9e8a8680-eda7-11e8-8f36-5aade30607fd.png)

[CreateEdge_body_API31.0.txt](https://github.com/vmware/pyvcloud/files/2604704/CreateEdge_body_API31.0.txt)

The creation of networks is well described in the chapter Create an Organization VDC Network in the most recent API version 31.0
[https://code.vmware.com/doc/preview?id=7348#/doc/GUID-A34DF1D3-7E5A-455E-8040-0F4FA31F2C39.html](url)

I'd love to have the networking part it in pyvcloud. As the networking is not covered I can't use teh pyvcloud to get our workflows automated and have to stick to raw API calls executed through the python requests library.

**Comment by shashim22** [comment]
Edge gateway feature is available now.

https://vmware.github.io/vcd-cli/vcd_gateway

-Shashi
