### ISSUE TITLE
Attempting to log into non-vCD server may generate confusing error message

### ISSUE THREAD

**Issue by hodgesrm** [vmware/pyvcloud#232]
Due to a configuration error one of my scripts tried to login to an NSX Manager instead of vCloud Director.  This results in the following stack trace.  (Credentials are suppressed.)

>python3 examples/system-info.py (nsx manager host ip) System (vcd sysadmin) (password)
> Logging in: host=(host ip), org=System, user=(vcd sysadmin)
> Traceback (most recent call last):
>   File "examples/system-info.py", line 46, in <module>
>     client.set_credentials(BasicLoginCredentials(user, org, password))
>   File "/var/jenkins/workspace/pyvcloud-pipeline/test-env/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 561, in set_credentials
>     auth=('%s@%s' % (creds.user, creds.org), creds.password))
>   File "/var/jenkins/workspace/pyvcloud-pipeline/test-env/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 724, in _do_request_prim
>     d = response.content.decode(self.fsencoding)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 60: ordinal not in range(128)

Logging into vCenter triggers a different stack trace:

>python3 examples/system-info.py (vcenter host ip) System (vcd sysadmin) (password)
> Logging in: host=(host ip), org=System, user=(vcd sysadmin)
> Traceback (most recent call last):
>   File "examples/system-info.py", line 46, in <module>
>     client.set_credentials(BasicLoginCredentials(user, org, password))
>   File "/var/jenkins/workspace/dev-pyvcloud-pipeline/test-env/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 572, in set_credentials
>     r) if r is not None else \
>   File "/var/jenkins/workspace/dev-pyvcloud-pipeline/test-env/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 529, in _get_response_request_id
>     return response.headers[self._REQUEST_ID_HDR_NAME]
>   File "/var/jenkins/workspace/dev-pyvcloud-pipeline/test-env/lib/python3.6/site-packages/requests/structures.py", line 54, in __getitem__
>     return self._store[key.lower()][1]
> KeyError: 'x-vmware-vcloud-request-id'

We need to do a better job of trapping these errors and returning a clear message.  One solution is to return an exception along the lines of "An unexpected login failure occurred" and log the detailed error in pyvcloud.log.

**Comment by pandeys** [comment]
We are throwing same exception as returned by VCD api response.
