### ISSUE TITLE
Roadmap to manage object metadata ?

### ISSUE THREAD

**Issue by kaneda-fr** [vmware/pyvcloud#256]
Hi,

Do you have on the roadmap the addition for the API call for managing metadata on objects ?

**Comment by hodgesrm** [comment]
Hi @kaneda-fr, it's not scheduled right now--we are focusing on documentation + build/test for the current dev cycle (through mid-summer) followed by networking capabilities such as deploying and managing edge routing services. 

What exactly would you like to see and would you or anyone else consider doing a pull request to implement it?  We gladly except outside contributions. 

Thanks! Robert

**Comment by kaneda-fr** [comment]
Hi @hodgesrm, We are storing metadata at org & VDC levels and this will allow us to stop using powershell to automate that data management.

Will look at the effort required to add this.

**Comment by hodgesrm** [comment]
Cool @kaneda-fr, just post questions or comments on this issue.  We're here to help.  :)

**Comment by kkkothari** [comment]
Vapp and VM metadata has done and  next release will have. Other part will done in future.
