### ISSUE TITLE
The method get resource of class PDVC is retrieving only one element for category

### ISSUE THREAD

**Issue by randalb1991** [vmware/pyvcloud#285]
When a PVDC has many resources(networks, storages profiles...), this method return only the first for each category:

Storage profiles returned by vCD API(and printed in pyvcloud logs)
![captura2](https://user-images.githubusercontent.com/10707967/45418053-de384200-b683-11e8-986f-af4ba481a4d1.PNG)

Storages profile returned by the method get_resource(only the first of them)
![captura1](https://user-images.githubusercontent.com/10707967/45418052-de384200-b683-11e8-9e4d-82143db5951e.PNG)

**Comment by rocknes** [comment]
Hi,

get_resource() method fetches the XML representation of the entire provider vdc from vCD. It's equivalent to objectifying the response of 

`GET /api/admin/extension/providervdc/{id}`

If you need to access the storage profiles supported by the pvdc
the code should look like

`for sp in pvdc.get_resource().StorageProfiles.ProviderVdcStorageProfile:
    # some code
    .
`

Can you please modify your code and let me know if all Storage profiles can be accessed using the modified code or not?

Etree generally lazy loads data and unless you ask it to load all the ProviderVdcStorageProfile nodes, it will show just the first one.

**Comment by randalb1991** [comment]
thanks @rocknes !

I can access to all storage profiles now, even when Etree loads only the first element.!

**Comment by randalb1991** [comment]
Issue closed
