### ISSUE TITLE
How insert (':') in tags using E ?

### ISSUE THREAD

**Issue by randalb1991** [vmware/pyvcloud#286]
How can I insert (':')  in XML tags for the request described in https://code.vmware.com/apis/220/vcloud#/doc/doc/operations/POST-UpdateVdcStorageClasses.html?

`<?xml version="1.0" encoding="UTF-8"?> 
<vcloud:UpdateVdcStorageProfiles xmlns:vcloud = "http://www.vmware.com/vcloud/v1.5" > 
     <vcloud:AddStorageProfile> 
         <vcloud:Enabled>true</vcloud:Enabled> 
         <vcloud:Units>MB</vcloud:Units> 
         <vcloud:Limit >300</vcloud:Limit> 
         <vcloud:Default>false</vcloud:Default> 
         <vcloud:ProviderVdcStorageProfile 
             href = "https://vcd_host/api/admin/pvdcStorageProfile/a7d4-ee4ef803e064" 
             name = "SILVER" 
             type = "application/vnd.vmware.admin.pvdcStorageProfile+xml"/> 
     </vcloud:AddStorageProfile> 
</vcloud:UpdateVdcStorageProfiles> 

`
Python show an error when ':' is inserted as part of the  tag:

`UpdateVdcStorageProfiles = E.vcloud:UpdateVdcStorageProfiles `

**Comment by rocknes** [comment]
_vcloud:_ in this case is the namespace of the tag.

If you are trying to create a new tag with the namespace _vcloud_ then simple `E.childTag` is good enough.
The element maker object E is defined in client.py as 
`
E = objectify.ElementMaker(
    annotate=False,
    namespace=NSMAP['vcloud'],
    nsmap={
        None: NSMAP['vcloud'],
        'xsi': NSMAP['xsi'],
        'xs': NSMAP['xs'],
        'ovf': NSMAP['ovf']
    })
`

On the other hand if you want to get a sub tag which has a different namespace than the parent node, then the correct way is to put the namesapce in front of the tag name inside curly braces i.e.

child = parent['{' + namespace + '}' + chil_tag_name]

**Comment by randalb1991** [comment]
@rocknes really thanks. As far as I understand, the first case described is enough for us. I tried again but it didn't work. My code is the follow:

`        UpdateVdcStorageProfiles = E.UpdateVdcStorageProfiles()
        AddStorageProfile = E.AddStorageProfile()
        Enabled = E.Enabled('true)
        Units = E.Units('MB')
        Limit = E.Limit(300)
        Default = E.Default('false)
        ProviderVdcStorageProfile=E.ProviderVdcStorageProfile(href=href_storage_profile,name=storage_profile_name, type='application/vnd.vmware.admin.pvdcStorageProfile+xml')

        AddStorageProfile.append(Enabled)
        AddStorageProfile.append(Units)
        AddStorageProfile.append(Limit)
        AddStorageProfile.append(Default)
        AddStorageProfile.append(ProviderVdcStorageProfile)

        UpdateVdcStorageProfiles.append(AddStorageProfile)`

but if I print the object, the xml generated is not the same as  XML described in the issue(Including vcloud:xxx):

`<?xml version="1.0" encoding="UTF-8"?>
<UpdateVdcStorageProfiles xmlns="http://www.vmware.com/vcloud/v1.5" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instan ce">
   <AddStorageProfile>
      <Enabled>true</Enabled>
      <Units>MB</Units>
      <Limit>300</Limit>
      <Default>false</Default>
      <ProviderVdcStorageProfile href="https://xxx/api/admin/pvdcStorageProfile/yyyy" name="SILVER" type="application/vnd.vmware.admin.pvdcStorageProfile+xml" />
   </AddStorageProfile>
</UpdateVdcStorageProfiles>`

Could you give as an example please?
