### ISSUE TITLE
Did it support Vcloud API version 5.5?

### ISSUE THREAD

**Issue by lucker6666** [vmware/pyvcloud#3]
Hi , i tried this,

vca = VCA()
vca.login('https://vclouddirectorhost.domain.com', 'username@organization', 'password', None, 'vcd', '5.5')
vcd = vca.get_vCloudDirector()
vapps = vcd.get_vApps()

but vcd didn't get the correct vCloudDirector instance, it gets None.

so i want to known that did the parseString function also worked for version 5.5?

THANKS

**Comment by pacogomez** [comment]
can you paste the stack trace?

**Comment by pacogomez** [comment]
we have tested it with version 5.5 and worked fine (also with 1.5, 5.1, 5.5 and 5.6), check if the login was successful (should return True), 
also enable logging with:


import logging
import httplib
httplib.HTTPConnection.debuglevel = 1
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True

**Comment by lucker6666** [comment]
From my environment seems below code returns a blank list for vdc_links, so i am not sure what happened

                        org = organizationType.parseString(response.content, True)
                        vdc_links = filter(lambda vdc_link: (vdc_link.name == self.org_name and vdc_link.type_ == 'application/vnd.vmware.vcloud.vdc+xml'), org.Link)
                        if vdc_links:
                            vcd = VCD(self.token, vdc_links[0].href, self.version, None, self.org_name)
                            return vcd

log as below,

DEBUG:requests.packages.urllib3.connectionpool:"GET /api/org/b9a2821c-e9e9-45ba-bbdf-cd1ca8e04d42 HTTP/1.1" 200 997
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 09 Jan 2015 03:27:23 GMT
header: Vary: Accept-Encoding
header: Date: Fri, 09 Jan 2015 03:27:24 GMT
header: Content-Type: application/vnd.vmware.vcloud.org+xml;version=5.5
header: Content-Encoding: gzip
header: Content-Length: 997
[]

Liang

**Comment by nlamirault** [comment]
I have this test : 

```python
if __name__ == '__main__':
    vca = vcloudair.VCA()
    vca.login(host, '%s@%s' % (user, org), password, None, 'vcd', '5.6')
    vcd = vca.get_vCloudDirector()
    vapps = vcd.get_vApps()
    print vapps
```

and the output : 

```bash
Traceback (most recent call last):
  File "./test.py", line 151, in <module>
    vcd = vca.get_vCloudDirector()
  File "/home/vagrant/Apps/pyvcloud/pyvcloud/vcloudair.py", line 180, in get_vCloudDirector
    vdcReference = self.get_vdcReference(serviceId, vdcId)
  File "/home/vagrant/Apps/pyvcloud/pyvcloud/vcloudair.py", line 157, in get_vdcReference
    serviceReferences = filter(lambda serviceReference: serviceReference.get_serviceId().lower() == serviceId.lower(), self.get_serviceReferences())
  File "/home/vagrant/Apps/pyvcloud/pyvcloud/vcloudair.py", line 147, in get_serviceReferences
    response = requests.get(self.host + "/api/vchs/services", headers=self._get_vchsHeaders())
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

```

**Comment by nlamirault** [comment]
Problem for my test comes from this line : 

```python
vdc_links = filter(lambda vdc_link: (vdc_link.name == self.org_name and vdc_link.type_ == 'application/vnd.vmware.vcloud.vdc+xml'), org.Link)
```                 
      
If i print the response content, i see that VDC does not match organization name:

```bash
<?xml version="1.0" encoding="UTF-8"?>
<Org xmlns="http://www.vmware.com/vcloud/v1.5" name="FCA_OAB01" id="urn:vcloud:org:19adf4a6-942d-4048-a36c-09a68161f0e9" type="application/vnd.vmware.vcloud.org+xml" href="https://...../api/org/19adf4a6-942d-4048-a36c-09a68161f0e9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://api.flexible-computing-adva
nced.orange-business.com/api/v1.5/schema/master.xsd">
    <Link rel="down" type="application/vnd.vmware.vcloud.vdc+xml" name="FCA_OAB01_VDC01" href="https://..../api/vdc/964f2a91-a5c9-4a51-bdce-16a0e7a43ea4"/>
    <Link rel="down" type="application/vnd.vmware.vcloud.vdc+xml" name="FCA_OAB01_VDC02" href="https://........./api/vdc/944eb979-858e-42d2-b347-bd10abef0731"/>
    <Link rel="down" type="application/vnd.vmware.vcloud.vdc+xml" name="FCA_OAB01_VDC03" href="https://........./api/vdc/b495cddf-40a2-4ab7-aef2-42f34b2a2663"/>
    <Link rel="down" type="application/vnd.vmware.vcloud.tasksList+xml" href="https://........./api/tasksList/19adf4a6-942d-4048-a36c-09a68161f0e9"/>
    <Link rel="down" type="application/vnd.vmware.vcloud.catalog+xml" name="ISO" href="https://........./api/catalog/51320131-478b-4611-809d-eb53f43b12db"/>
```

Replace the filter with this : 
```python
vdc_links = filter(lambda vdc_link: (vdc_link.type_ == 'application/vnd.vmware.vcloud.vdc+xml'), org.Link)
```

It works fine.

**Comment by pacogomez** [comment]
I think this is fixed now with the last commit.

will have to provide the vdc name like this:

for datacenter in vca.get_vdcReferences():
    print datacenter.name
vcd = vca.get_vCloudDirector(vdcId='mydatacenter')
