### ISSUE TITLE
OAUTH & SAML authentication 

### ISSUE THREAD

**Issue by kaneda-fr** [vmware/pyvcloud#302]
Hi,

Is there any plan or work in progress to support OAUTH or SAML token based authentication ?

Thanks,

**Comment by rocknes** [comment]
Hi Sebastien,

Right now, we don't have any plans to support OAUTH or SAML but they are in our future roadmap.

Regards
Aritra Sen

**Comment by mgaruccio** [comment]
+1 for this, it would be great if our users didn't need to create non-2FA users in order to use pyvcloud and it's associated tools

**Comment by chitashvili** [comment]
This is really very good feature +1

**Comment by dev-dom** [comment]
merge #593 takes care of ldap, saml, leases and all extended settings used in the org creation.
Best Regards,
Domenico
