### ISSUE TITLE
error running list_vdc_resources exampple

### ISSUE THREAD

**Issue by chechuironman** [vmware/pyvcloud#332]
(.venv) Ninja:pyvcloud chechu$ python examples/list-vdc-resources.py x.x.x.x  System Administrator ******
Traceback (most recent call last):
  File "examples/list-vdc-resources.py", line 18, in <module>
    from pyvcloud.vcd.client import BasicLoginCredentials
  File "/Users/chechu/ICP/pyvcloud/pyvcloud/vcd/client.py", line 1086
    raise OperationNotSupportedException from e

**Comment by kkkothari** [comment]
Hi @chechuironman ,
Are you still getting this issue or it's you script issue?
Can you please let us know so we can look into this.

**Comment by pandeys** [comment]
No response from author. Closing the thread.
