### ISSUE TITLE
How to wait for catalog deletion?

### ISSUE THREAD

**Issue by andrew-ni** [vmware/pyvcloud#334]
Relevant for CSE system testing.

For example:
```python
org.delete_catalog(catalog_name)
# currently no way to wait for catalog deletion?
org.reload
# org resource does not reflect that the catalog has been deleted
```

- Even if I use `time.sleep(10)`, and reload after, the org is still not updated.
- Cannot use `client.get_task_monitor().wait_for_success(task)` because we don't have the task.

Is there a current way to wait for catalog deletion?

**Comment by chaitanya118** [comment]
Its seems to be a issue with the code.
the delete_catalog method is not returning the task.

alternatively, until the issue is fixed, you can try to get the catalog by name and access the task from it.
If you do not get the catalog, you can consider it as deleted.
the pseudo code may look like.

```
catalog = org.get_catalog('name')
task = catalog['{' + NSMAP['vcloud'] + '}Tasks'].Task[0]
        admin_client.get_task_monitor().wait_for_success(task=task)
```

**Comment by pandeys** [comment]
We will fix this issue.
