### ISSUE TITLE
The framework is not working for vCD version 6.4 and above

### ISSUE THREAD

**Issue by VarunUmesh** [vmware/pyvcloud#37]
Hello,

I tried to use the framework for vCD version 6.4 and above and it does not work, could you please take a look at it on priority?

Thanks!

**Comment by VarunUmesh** [comment]
I see the following error, when i enable the debug logs:

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): xxx.xxx.xxx.xxx
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:730: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html (This warning will only appear once by default.)
  InsecureRequestWarning)
send: 'POST /api/sessions HTTP/1.1\r\nHost: xxx.xxx.xxx.xxx\r\nContent-Length: 0\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/*+xml;version=5.7\r\nUser-Agent: python-requests/2.4.3 CPython/2.7.6 Linux/3.16.0-30-generic\r\nConnection: keep-alive\r\nAuthorization: Basic YWRtaW5pc3RyYXRvckBhY3R1YWxob3N0czpjYSRoYzB3\r\n\r\n'
reply: 'HTTP/1.1 401 Unauthorized\r\n'
header: Date: Tue, 31 Mar 2015 19:09:55 GMT
header: X-VMWARE-VCLOUD-REQUEST-ID: 48830fe5-1c8c-4b04-944e-3d8714b8ea00
header: WWW-Authenticate: Basic realm="vCloud", SIGN realm="vCloud", Bearer realm="vCloud"
header: Content-Length: 0
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/sessions HTTP/1.1" 401 0

The same works fine, if i use a rest client and test.

Any idea what i might be doing wrong?

**Comment by pacogomez** [comment]
for standalone vCloud Director, make sure you are sending the right login information, for example:

host='p1v21-vcd.vchs.vmware.com'
username = os.environ['VCAUSER']
password = os.environ['PASSWORD']
org = 'AppServices'

#sample login sequence on vCloud Director standalone
vca = VCA(host=host, username=username, service_type='vcd', version='5.6', verify=False)

#first login, with password and org name
result = vca.login(password=password, org=org)
print_vca(vca)

Also, try with version='6.4'

**Comment by VarunUmesh** [comment]
Actually, it was a mistake from my side, I was passing the org along with the user name [example: user_name@org]. I did not realize that the org was being concatenated with the user name, with in the code. Apologies for the mistake. Also, it works with vCD version 6.4+, you can update this in the Readme file.

**Comment by pacogomez** [comment]
Thanks Varun!
