### ISSUE TITLE
vcd_login connection question

### ISSUE THREAD

**Issue by pjamelot** [vmware/pyvcloud#393]
Hello,
  pyvcloud==20.0.2
  vcd=8.2
  python 3.6.3
  
I can't connect to my vcloud with my config (I used api_version 27.0), I tried the same credentials with vcd-cli and it works fine.
Could you help me on this issue  ?

python -m unittest vcd_login
E
======================================================================
ERROR: setUpClass (vcd_login.TestLogin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/pyvcloud/vcd/test.py", line 50, in setUpClass
    cls.config['vcd']['password']))
  File "/root/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 819, in set_credentials
    sc, self._get_response_request_id(response), r)
  File "/root/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 924, in _response_code_to_exception
    raise AccessForbiddenException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.AccessForbiddenException: Status code: 403/ACCESS_TO_RESOURCE_IS_FORBIDDEN, Access is forbidden (request id: ae950f43-ef8a-4d97-b078-724495e8b211)

----------------------------------------------------------------------
Ran 0 tests in 0.076s

**Comment by chitashvili** [comment]
Hello could you give more information like what you provide as Org? What is your user access rights? Is it Org specific or it is Master tenant from System org?

**Comment by Cylindric** [comment]
I am having a similar problem. I can use the creds in the web UI, the REST API and from vcd-cli successfully, but I'm getting this 403 with the Python lib.
The user is a local user in System with full admin.
For 'org' I'm specifying 'system'.

**Comment by Cylindric** [comment]
I think my problem was a simple error on my part - I was providing a full URL such as https://my.vdc.org/api, instead of just the name. Seems to be working now.

**Comment by kkkothari** [comment]
Hi @pjamelot , @Cylindric 
The PYSDK Support only API version 29.0, 30.0, 31.0, 32.0 and 33.0
