### ISSUE TITLE
Create VApp with network

### ISSUE THREAD

**Issue by suthanvs** [vmware/pyvcloud#40]
Now VApp is getting created without any proper network , no implementation in Vapp to accept networks.I can implement it , what is the procedure now?

**Comment by pacogomez** [comment]
clone the repo, add the implementation and submit a pull request. once we review it and accept it, will add it to the SDK. Thanks,

**Comment by suthanvs** [comment]
sure , thanks

**Comment by suthanvs** [comment]
is there a IRC channel to communicate ?

On Wed, Apr 8, 2015 at 2:26 PM, Paco Gómez <notifications@github.com> wrote:

> clone the repo, add the implementation and submit a pull request. once we
> review it and accept it, will add it to the SDK. Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vmware/pyvcloud/issues/40#issuecomment-91011438>.
>



-- 
Regards,
Suthan

**Comment by gwesterfieldjr** [comment]
@suthanvs I have implemented the same in the following PR:https://github.com/vmware/pyvcloud/pull/226

You can now pass the network adapter type when creating a vApp from a template using vdc.instanciate_vapp

**Comment by hodgesrm** [comment]
Closing following merge of https://github.com/vmware/pyvcloud/pull/226.
