### ISSUE TITLE
Support for custom LDAP settings

### ISSUE THREAD

**Issue by cdivitotawela** [vmware/pyvcloud#406]
Hi Team,

I have a requirement to configure custom LDAP settings at the time of the organization creation. I cannot find a way to do that via library. When I check the REST API reference it has OrgLdapSettings element. Is configuring LDAP not available in the module?

Reference:
https://www.vmware.com/support/vcd/doc/rest-api-doc-1.5-html/types/AdminOrgType.html

Thanks,
Chaminda

**Comment by cdivitotawela** [comment]
Looked into code and on method System.create_org we simply add empty setting element. I will see whether I will be able to make a change (and PR) to support adding settings at the time of the creation.

org_params = E.AdminOrg(
            E.FullName(full_org_name),
            E.IsEnabled(is_enabled),
            E.Settings,
            name=org_name)

**Comment by chitashvili** [comment]
Hello I am also looking for this option to configure not only LDAP but all rest options. 
https://github.com/vmware/pyvcloud/issues/337

I Am not so good in development to create pull request but I was playing around with some option. One was to extend create_org / update_org to support Settings change.

Last sample what I managed to do is following:

```
    def create_org(self, org_name, full_org_name, is_enabled=False):
        """Create new organization.

        :param str org_name: name of the organization.
        :param str full_org_name: full name of the organization.
        :param bool is_enabled: enable organization if True

        :return: an object containing EntityType.ADMIN_ORG XML data which
            represents the newly created organization.

        :rtype: lxml.objectify.ObjectifiedElement
        """
        if self.admin_resource is None:
            self.admin_resource = self.client.get_resource(self.admin_href)
        org_params = E.AdminOrg(
            E.FullName(full_org_name),
            E.IsEnabled(is_enabled),
            E.Settings(
                E.OrgGeneralSettings(
                    E.CanPublishCatalogs(False),
                    E.CanPublishExternally(False),
                    E.CanSubscribe(False),
                    E.DeployedVMQuota(0),
                    E.StoredVmQuota(0),
                    E.UseServerBootSequence(False),
                    E.DelayAfterPowerOnSeconds(0)),
                E.VAppLeaseSettings(
                    E.DeleteOnStorageLeaseExpiration(True),
                    E.DeploymentLeaseSeconds(0),
                    E.StorageLeaseSeconds(0),
                    E.PowerOffOnRuntimeLeaseExpiration(True)),
                E.VAppTemplateLeaseSettings(
                    E.DeleteOnStorageLeaseExpiration(True),
                    E.StorageLeaseSeconds(0))),
            name=org_name)
        return self.client.post_linked_resource(
            self.admin_resource, RelationType.ADD, EntityType.ADMIN_ORG.value,
            org_params)
```

There is no arguments on provide it is hardcoded now.

Sorry for such code as I pointed I am not developer but this is kinds of work around what can be maybe useful for someone for PR.

**Comment by cdivitotawela** [comment]
@chitashvili Thanks for your notes. Until a proper solution available I have extended the class and override the method with my own implementation. I have solution currently being used and need to create a PR.

I wonder if we add all the settings at the creation time, it will have very large number of input to the method. So wondering whether it would be better approach to leave the create_org simple and add separate methods to update the custom LDAP settings etc.

**Comment by chitashvili** [comment]
I 100% agree with you that if we can have separate method to update  settings like:
```
PUT /admin/org/{id}/settings
application/vnd.vmware.admin.orgSettings+xml 
```
Rather than overriding AdmirOrg for that 
Or maybe separate methods for specific settings:
```
PUT /admin/org/{id}/settings/vAppLeaseSettings
application/vnd.vmware.admin.vAppLeaseSettings+xml
```
AND
```
PUT /admin/org/{id}/settings/general
application/vnd.vmware.admin.organizationGeneralSettings+xml
```

Thanks you in advance for PR I really need this functionality and will appreciate your help.

**Comment by cdivitotawela** [comment]
Initial version to update LDAP settings for an organization is here in my repo. 
https://github.com/cdivitotawela/pyvcloud/tree/ldap-configuration

Here is an example to use. I need to more time to add unit tests.
```
import requests
from pyvcloud.vcd.client import BasicLoginCredentials
from pyvcloud.vcd.client import Client
from pyvcloud.vcd.org import Org

requests.packages.urllib3.disable_warnings()

vcd_host = 'vcd.example.com'
api_version = '31.0'
username = 'admin'
password = 'MyPassword'
org_name = 'OrgName'

# Client creation
client = Client(
            vcd_host,
            api_version=api_version,
            verify_ssl_certs=False,
            log_file='my-test.log',
            log_requests=True,
            log_headers=True,
            log_bodies=True)

client.set_credentials(BasicLoginCredentials(username,'System',password))
org_objectify = client.get_org_by_name(org_name)
org = Org(client, href=org_objectify.get('href'))
org.update_ldap_settings('CUSTOM',cus_hostname='example.com',cus_port=234, cus_isssl=True,cus_user_email='user@gmail.com')
```

**Comment by chitashvili** [comment]
@cdivitotawela thank you for contribution I will check it our in close future!

**Comment by cdivitotawela** [comment]
@chitashvili here is the PR. It support configuring lease and ldap when organization is created. I have also implemented import groups from the LDAP. I will wait for this PR to be merged to PR that change.

**Comment by chitashvili** [comment]
Hello @cdivitotawela, i saw it. That is awesome thank you for PR. If you also will have some time for general setting that will be awesome!

**Comment by pandeys** [comment]
We will take it in our backlog.

**Comment by dev-dom** [comment]
Also merge #593 takes care of ldap, saml, leases and all extended settings used in the org creation.
Best Regards,
Domenico

**Comment by manuelmazzuola** [comment]
> @chitashvili I have also implemented import groups from the LDAP.

@cdivitotawela Can you share that branch?

**Comment by azzamsa** [comment]
any update?
