### ISSUE TITLE
Create is failing with vmname

### ISSUE THREAD

**Issue by suthanvs** [vmware/pyvcloud#41]
When I try to create vapp with vmname , its failing with error as "BAD REQUEST" , Invalid content was found starting with element 'SourcedItem' .

**Comment by lasko** [comment]
Having this same issue.

can't create the vApp, <?xml version="1.0" encoding="UTF-8"?>
<Error xmlns="http://www.vmware.com/vcloud/v1.5" minorErrorCode="BAD_REQUEST" message="Bad request
 - Unexpected JAXB Exception
 - cvc-complex-type.2.4.a: Invalid content was found starting with element 'SourcedItem'. One of '{&quot;http://www.vmware.com/vcloud/v1.5&quot;:IsSourceDelete, &quot;http://www.vmware.com/vcloud/v1.5&quot;:SourcedVmInstantiationParams, &quot;http://www.vmware.com/vcloud/v1.5&quot;:AllEULAsAccepted}' is expected." majorErrorCode="400" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ......................................

**Comment by suthanvs** [comment]
Yeah lasko , I have fixed it. Its basically because of payload while making a request . I have fixed this issue on my fork but couldn't push it as I don't have permissions

**Comment by pacogomez** [comment]
I'll review the pull request and will integrated it into the master branch. Thanks

**Comment by lasko** [comment]
Whats the status of this being integrated into the master branch?

**Comment by ACCORDS-PLATFORM** [comment]
Hello, 
I notified the same issue when reconfiguring CPUs and MEMORY

###REQUEST:
 POST  https://vcloudcell.prologue.prl/api/vdc/351bdd7f-8197-4c98-8c90-35b154aee3ab/action/instantiateVAppTemplate

Authorization: Basic YWRtaW5wcmxAcHJvbG9ndWU6UHIwbDBndWU6MjAxNA==
Accept: application/*+xml;version=5.5
Content-Type: application/vnd.vmware.vcloud.instantiateVAppTemplateParams+xml

BODY
<?xml version="1.0" encoding="UTF-8"?><InstantiateVAppTemplateParams xmlns="http://www.vmware.com/vcloud/v1.5" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1"
xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" name="VM02" powerOn="false" deploy="false"><Source href="https://vcloudcell.prologue.prl/api/vAppTemplate/vappTemplate-087f6cf6-839d-4f75-802a-56886962bb3d"/>
<SourcedItem><Source/><InstantiationParams><ovf:VirtualHardwareSection><ovf:Info>Virtual hardware requirements</ovf:Info>
<ovf:Item><rasd:AllocationUnits>hertz * 10^6</rasd:AllocationUnits><rasd:Description>Number of Virtual CPUs
</rasd:Description><rasd:ElementName>2 virtual CPU(s)</rasd:ElementName>
<rasd:InstanceID>1</rasd:InstanceID>
<rasd:ResourceType>3</rasd:ResourceType>
<rasd:VirtualQuantity>2</rasd:VirtualQuantity>
</ovf:Item><ovf:Item><rasd:AllocationUnits>byte * 2^20</rasd:AllocationUnits>
<rasd:Description>Memory Size</rasd:Description><rasd:ElementName>512 MB of memory</rasd:ElementName><rasd:InstanceID>2</rasd:InstanceID><rasd:ResourceType>4</rasd:ResourceType><rasd:VirtualQuantity>512</rasd:VirtualQuantity></ovf:Item></ovf:VirtualHardwareSection></InstantiationParams></SourcedItem><AllEULAsAccepted>true</AllEULAsAccepted></InstantiateVAppTemplateParams>


###RESPONSE:
<?xml version="1.0" encoding="UTF-8" ?>
<Error minorErrorCode="BAD_REQUEST" message="Requête incorrecte - Unexpected JAXB Exception - cvc-complex-type.2.4.a: Invalid content was found starting with element 'SourcedItem'. One of '{"http://www.vmware.com/vcloud/v1.5":IsSourceDelete, "http://www.vmware.com/vcloud/v1.5":SourcedVmInstantiationParams, "http://www.vmware.com/vcloud/v1.5":AllEULAsAccepted}' is expected." majorErrorCode="400" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://172.17.117.108/api/v1.5/schema/master.xsd" />

**Comment by ACCORDS-PLATFORM** [comment]
Hello, 
I notified the same issue when reconfiguring CPUs and MEMORY

###REQUEST:
POST https://vcloudcell.prologue.prl/api/vdc/351bdd7f-8197-4c98-8c90-35b154aee3ab/action/instantiateVAppTemplate

Authorization: Basic YWRtaW5wcmxAcHJvbG9ndWU6UHIwbDBndWU6MjAxNA==
Accept: application/*+xml;version=5.5
Content-Type: application/vnd.vmware.vcloud.instantiateVAppTemplateParams+xml

BODY
<?xml version="1.0" encoding="UTF-8"?> xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" name="VM02" powerOn="false" deploy="false">
ovf:VirtualHardwareSectionovf:InfoVirtual hardware requirements/ovf:Info
ovf:Itemrasd:AllocationUnitshertz * 10^6/rasd:AllocationUnitsrasd:DescriptionNumber of Virtual CPUs
/rasd:Descriptionrasd:ElementName2 virtual CPU(s)/rasd:ElementName
rasd:InstanceID1/rasd:InstanceID
rasd:ResourceType3/rasd:ResourceType
rasd:VirtualQuantity2/rasd:VirtualQuantity
/ovf:Itemovf:Itemrasd:AllocationUnitsbyte * 2^20/rasd:AllocationUnits
rasd:DescriptionMemory Size/rasd:Descriptionrasd:ElementName512 MB of memory/rasd:ElementNamerasd:InstanceID2/rasd:InstanceIDrasd:ResourceType4/rasd:ResourceTyperasd:VirtualQuantity512/rasd:VirtualQuantity/ovf:Item/ovf:VirtualHardwareSectiontrue

###RESPONSE:
<?xml version="1.0" encoding="UTF-8" ?>
<Error minorErrorCode="BAD_REQUEST" message="Requête incorrecte - Unexpected JAXB Exception - cvc-complex-type.2.4.a: Invalid content was found starting with element 'SourcedItem'. One of '{"http://www.vmware.com/vcloud/v1.5":IsSourceDelete, "http://www.vmware.com/vcloud/v1.5":SourcedVmInstantiationParams, "http://www.vmware.com/vcloud/v1.5":AllEULAsAccepted}' is expected." majorErrorCode="400" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://172.17.117.108/api/v1.5/schema/master.xsd" />

**Comment by btalebali** [comment]
Hello, 
I notified the same issue when reconfiguring CPUs and MEMORY
###REQUEST:
POST https://vcloudcell.prologue.prl/api/vdc/351bdd7f-8197-4c98-8c90-35b154aee3ab/action/instantiateVAppTemplate
Authorization: Basic YWRtaW5wcmxAcHJvbG9ndWU6UHIwbDBndWU6MjAxNA==
Accept: application/*+xml;version=5.5
Content-Type: application/vnd.vmware.vcloud.instantiateVAppTemplateParams+xml
BODY
<?xml version="1.0" encoding="UTF-8"?> xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" name="VM02" powerOn="false" deploy="false">
ovf:VirtualHardwareSectionovf:InfoVirtual hardware requirements/ovf:Info
ovf:Itemrasd:AllocationUnitshertz * 10^6/rasd:AllocationUnitsrasd:DescriptionNumber of Virtual CPUs
/rasd:Descriptionrasd:ElementName2 virtual CPU(s)/rasd:ElementName
rasd:InstanceID1/rasd:InstanceID
rasd:ResourceType3/rasd:ResourceType
rasd:VirtualQuantity2/rasd:VirtualQuantity
/ovf:Itemovf:Itemrasd:AllocationUnitsbyte * 2^20/rasd:AllocationUnits
rasd:DescriptionMemory Size/rasd:Descriptionrasd:ElementName512 MB of memory/rasd:ElementNamerasd:InstanceID2/rasd:InstanceIDrasd:ResourceType4/rasd:ResourceTyperasd:VirtualQuantity512/rasd:VirtualQuantity/ovf:Item/ovf:VirtualHardwareSectiontrue
###RESPONSE:
<?xml version="1.0" encoding="UTF-8" ?>
<?xml version="1.0" encoding="UTF-8" ?>
<Error minorErrorCode="BAD_REQUEST" message="Requête incorrecte - Unexpected JAXB Exception - cvc-complex-type.2.4.a: Invalid content was found starting with element 'SourcedItem'. One of '{"http://www.vmware.com/vcloud/v1.5":IsSourceDelete, "http://www.vmware.com/vcloud/v1.5":SourcedVmInstantiationParams, "http://www.vmware.com/vcloud/v1.5":AllEULAsAccepted}' is expected." majorErrorCode="400" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://172.17.117.108/api/v1.5/schema/master.xsd" />

**Comment by btalebali** [comment]
Hello, 
I notified the same issue when reconfiguring CPUs and MEMORY
###REQUEST:
POST https://vcloudcell.prologue.prl/api/vdc/351bdd7f-8197-4c98-8c90-35b154aee3ab/action/instantiateVAppTemplate
BODY
<?xml version="1.0" encoding="UTF-8"?> xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" name="VM02" powerOn="false" deploy="false">
ovf:VirtualHardwareSectionovf:InfoVirtual hardware requirements/ovf:Info
ovf:Itemrasd:AllocationUnitshertz * 10^6/rasd:AllocationUnitsrasd:DescriptionNumber of Virtual CPUs
/rasd:Descriptionrasd:ElementName2 virtual CPU(s)/rasd:ElementName
rasd:InstanceID1/rasd:InstanceID
rasd:ResourceType3/rasd:ResourceType
rasd:VirtualQuantity2/rasd:VirtualQuantity
/ovf:Itemovf:Itemrasd:AllocationUnitsbyte * 2^20/rasd:AllocationUnits
rasd:DescriptionMemory Size/rasd:Descriptionrasd:ElementName512 MB of memory/rasd:ElementNamerasd:InstanceID2/rasd:InstanceIDrasd:ResourceType4/rasd:ResourceTyperasd:VirtualQuantity512/rasd:VirtualQuantity/ovf:Item/ovf:VirtualHardwareSectiontrue

###RESPONSE:
<?xml version="1.0" encoding="UTF-8" ?>
<Error minorErrorCode="BAD_REQUEST" message="Requête incorrecte - Unexpected JAXB Exception - cvc-complex-type.2.4.a: Invalid content was found starting with element 'SourcedItem'. One of '{"http://www.vmware.com/vcloud/v1.5":IsSourceDelete, "http://www.vmware.com/vcloud/v1.5":SourcedVmInstantiationParams, "http://www.vmware.com/vcloud/v1.5":AllEULAsAccepted}' is expected." majorErrorCode="400" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://172.17.117.108/api/v1.5/schema/master.xsd" />

**Comment by btalebali** [comment]
Hello, 
I notified the same issue when reconfiguring CPUs and MEMORY
#REQUEST:
POST https://vcloudcell.prologue.prl/api/vdc/351bdd7f-8197-4c98-8c90-35b154aee3ab/action/instantiateVAppTemplate
BODY
<?xml version="1.0" encoding="UTF-8"?> xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" name="VM02" powerOn="false" deploy="false">
ovf:VirtualHardwareSectionovf:InfoVirtual hardware requirements/ovf:Info
ovf:Itemrasd:AllocationUnitshertz * 10^6/rasd:AllocationUnitsrasd:DescriptionNumber of Virtual CPUs
/rasd:Descriptionrasd:ElementName2 virtual CPU(s)/rasd:ElementName
rasd:InstanceID1/rasd:InstanceID
rasd:ResourceType3/rasd:ResourceType
rasd:VirtualQuantity2/rasd:VirtualQuantity
/ovf:Itemovf:Itemrasd:AllocationUnitsbyte * 2^20/rasd:AllocationUnits
rasd:DescriptionMemory Size/rasd:Descriptionrasd:ElementName512 MB of memory/rasd:ElementNamerasd:InstanceID2/rasd:InstanceIDrasd:ResourceType4/rasd:ResourceTyperasd:VirtualQuantity512/rasd:VirtualQuantity/ovf:Item/ovf:VirtualHardwareSectiontrue
#RESPONSE:
<?xml version="1.0" encoding="UTF-8" ?>
<Error minorErrorCode="BAD_REQUEST" message="Requête incorrecte - Unexpected JAXB Exception - cvc-complex-type.2.4.a: Invalid content was found starting with element 'SourcedItem'. One of '{"http://www.vmware.com/vcloud/v1.5":IsSourceDelete, "http://www.vmware.com/vcloud/v1.5":SourcedVmInstantiationParams, "http://www.vmware.com/vcloud/v1.5":AllEULAsAccepted}' is expected." majorErrorCode="400" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://172.17.117.108/api/v1.5/schema/master.xsd" />

**Comment by btalebali** [comment]
Hello, 
I notified the same issue when reconfiguring CPUs and MEMORY
###REQUEST:
POST https://vcloudcell.prologue.prl/api/vdc/351bdd7f-8197-4c98-8c90-35b154aee3ab/action/instantiateVAppTemplate
BODY
<?xml version="1.0" encoding="UTF-8"?> xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" name="VM02" powerOn="false" deploy="false">
ovf:VirtualHardwareSectionovf:InfoVirtual hardware requirements/ovf:Info
ovf:Itemrasd:AllocationUnitshertz * 10^6/rasd:AllocationUnitsrasd:DescriptionNumber of Virtual CPUs
/rasd:Descriptionrasd:ElementName2 virtual CPU(s)/rasd:ElementName
rasd:InstanceID1/rasd:InstanceID
rasd:ResourceType3/rasd:ResourceType
rasd:VirtualQuantity2/rasd:VirtualQuantity
/ovf:Itemovf:Itemrasd:AllocationUnitsbyte * 2^20/rasd:AllocationUnits
rasd:DescriptionMemory Size/rasd:Descriptionrasd:ElementName512 MB of memory/rasd:ElementNamerasd:InstanceID2/rasd:InstanceIDrasd:ResourceType4/rasd:ResourceTyperasd:VirtualQuantity512/rasd:VirtualQuantity/ovf:Item/ovf:VirtualHardwareSectiontrue

###RESPONSE:
<?xml version="1.0" encoding="UTF-8" ?><Error minorErrorCode="BAD_REQUEST" message="Requête incorrecte - Unexpected JAXB Exception - cvc-complex-type.2.4.a: Invalid content was found starting with element 'SourcedItem'. One of '{"http://www.vmware.com/vcloud/v1.5":IsSourceDelete, "http://www.vmware.com/vcloud/v1.5":SourcedVmInstantiationParams, "http://www.vmware.com/vcloud/v1.5":AllEULAsAccepted}' is expected." majorErrorCode="400" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://172.17.117.108/api/v1.5/schema/master.xsd" />

**Comment by btalebali** [comment]
Hello, 
I notified the same issue when reconfiguring CPUs and MEMORY
###REQUEST:
POST https://vcloudcell.prologue.prl/api/vdc/351bdd7f-8197-4c98-8c90-35b154aee3ab/action/instantiateVAppTemplate
BODY
<?xml version="1.0" encoding="UTF-8"?> xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" name="VM02" powerOn="false" deploy="false">
ovf:VirtualHardwareSectionovf:InfoVirtual hardware requirements/ovf:Info
ovf:Itemrasd:AllocationUnitshertz * 10^6/rasd:AllocationUnitsrasd:DescriptionNumber of Virtual CPUs
/rasd:Descriptionrasd:ElementName2 virtual CPU(s)/rasd:ElementName
rasd:InstanceID1/rasd:InstanceID
rasd:ResourceType3/rasd:ResourceType
rasd:VirtualQuantity2/rasd:VirtualQuantity
/ovf:Itemovf:Itemrasd:AllocationUnitsbyte * 2^20/rasd:AllocationUnits
rasd:DescriptionMemory Size/rasd:Descriptionrasd:ElementName512 MB of memory/rasd:ElementNamerasd:InstanceID2/rasd:InstanceIDrasd:ResourceType4/rasd:ResourceTyperasd:VirtualQuantity512/rasd:VirtualQuantity/ovf:Item/ovf:VirtualHardwareSectiontrue
###RESPONSE:
<?xml version="1.0" encoding="UTF-8" ?>
<Error minorErrorCode="BAD_REQUEST" message="Requête incorrecte - Unexpected JAXB Exception - cvc-complex-type.2.4.a: Invalid content was found starting with element 'SourcedItem'. One of '{"http://www.vmware.com/vcloud/v1.5":IsSourceDelete, "http://www.vmware.com/vcloud/v1.5":SourcedVmInstantiationParams, "http://www.vmware.com/vcloud/v1.5":AllEULAsAccepted}' is expected." majorErrorCode="400" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://172.17.117.108/api/v1.5/schema/master.xsd" />

**Comment by btalebali** [comment]
Just to complete response:

###RESPONSE:
<?xml version="1.0" encoding="UTF-8" ?>
<Error minorErrorCode="BAD_REQUEST" message="Requête incorrecte - Unexpected JAXB Exception - cvc-complex-type.2.4.a: Invalid content was found starting with element 'SourcedItem'. One of '{"http://www.vmware.com/vcloud/v1.5":IsSourceDelete, "http://www.vmware.com/vcloud/v1.5":SourcedVmInstantiationParams, "http://www.vmware.com/vcloud/v1.5":AllEULAsAccepted}' is expected." majorErrorCode="400" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://172.17.117.108/api/v1.5/schema/master.xsd" />

**Comment by btalebali** [comment]
Hello, 
I notified the same issue when reconfiguring CPUs and MEMORY
###REQUEST:
POST https://vcloudcell.prologue.prl/api/vdc/351bdd7f-8197-4c98-8c90-35b154aee3ab/action/instantiateVAppTemplate
BODY
<?xml version="1.0" encoding="UTF-8"?> xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" name="VM02" powerOn="false" deploy="false">
ovf:VirtualHardwareSectionovf:InfoVirtual hardware requirements/ovf:Info
ovf:Itemrasd:AllocationUnitshertz * 10^6/rasd:AllocationUnitsrasd:DescriptionNumber of Virtual CPUs
/rasd:Descriptionrasd:ElementName2 virtual CPU(s)/rasd:ElementName
rasd:InstanceID1/rasd:InstanceID
rasd:ResourceType3/rasd:ResourceType
rasd:VirtualQuantity2/rasd:VirtualQuantity
/ovf:Itemovf:Itemrasd:AllocationUnitsbyte * 2^20/rasd:AllocationUnits
rasd:DescriptionMemory Size/rasd:Descriptionrasd:ElementName512 MB of memory/rasd:ElementNamerasd:InstanceID2/rasd:InstanceIDrasd:ResourceType4/rasd:ResourceTyperasd:VirtualQuantity512/rasd:VirtualQuantity/ovf:Item/ovf:VirtualHardwareSectiontrue

###RESPONSE:

<Error minorErrorCode="BAD_REQUEST" message="Requête incorrecte - Unexpected JAXB Exception - cvc-complex-type.2.4.a: Invalid content was found starting with element 'SourcedItem'. One of '{"http://www.vmware.com/vcloud/v1.5":IsSourceDelete, "http://www.vmware.com/vcloud/v1.5":SourcedVmInstantiationParams, "http://www.vmware.com/vcloud/v1.5":AllEULAsAccepted}' is expected." majorErrorCode="400" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://172.17.117.108/api/v1.5/schema/master.xsd" />

**Comment by btalebali** [comment]
Hello, 
I notified the same issue when reconfiguring CPUs and MEMORY

REQUEST:
POST https://vcloudcell.prologue.prl/api/vdc/351bdd7f-8197-4c98-8c90-35b154aee3ab/action/instantiateVAppTemplate
BODY
<?xml version="1.0" encoding="UTF-8"?> xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" name="VM02" powerOn="false" deploy="false">
ovf:VirtualHardwareSectionovf:InfoVirtual hardware requirements/ovf:Info
ovf:Itemrasd:AllocationUnitshertz * 10^6/rasd:AllocationUnitsrasd:DescriptionNumber of Virtual CPUs
/rasd:Descriptionrasd:ElementName2 virtual CPU(s)/rasd:ElementName
rasd:InstanceID1/rasd:InstanceID
rasd:ResourceType3/rasd:ResourceType
rasd:VirtualQuantity2/rasd:VirtualQuantity
/ovf:Itemovf:Itemrasd:AllocationUnitsbyte * 2^20/rasd:AllocationUnits
rasd:DescriptionMemory Size/rasd:Descriptionrasd:ElementName512 MB of memory/rasd:ElementNamerasd:InstanceID2/rasd:InstanceIDrasd:ResourceType4/rasd:ResourceTyperasd:VirtualQuantity512/rasd:VirtualQuantity/ovf:Item/ovf:VirtualHardwareSectiontrue

RESPONSE:

<Error minorErrorCode="BAD_REQUEST" message="Requête incorrecte - Unexpected JAXB Exception - cvc-complex-type.2.4.a: Invalid content was found starting with element 'SourcedItem'. One of '{"http://www.vmware.com/vcloud/v1.5":IsSourceDelete, "http://www.vmware.com/vcloud/v1.5":SourcedVmInstantiationParams, "http://www.vmware.com/vcloud/v1.5":AllEULAsAccepted}' is expected." majorErrorCode="400" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://172.17.117.108/api/v1.5/schema/master.xsd" />

**Comment by btalebali** [comment]
Hello, 
I notified the same issue when reconfiguring CPUs and MEMORY
REQUEST:
POST https://vcloudcell.prologue.prl/api/vdc/351bdd7f-8197-4c98-8c90-35b154aee3ab/action/instantiateVAppTemplate
BODY
<?xml version="1.0" encoding="UTF-8"?> xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" name="VM02" powerOn="false" deploy="false">
ovf:VirtualHardwareSectionovf:InfoVirtual hardware requirements/ovf:Info
ovf:Itemrasd:AllocationUnitshertz * 10^6/rasd:AllocationUnitsrasd:DescriptionNumber of Virtual CPUs
/rasd:Descriptionrasd:ElementName2 virtual CPU(s)/rasd:ElementName
rasd:InstanceID1/rasd:InstanceID
rasd:ResourceType3/rasd:ResourceType
rasd:VirtualQuantity2/rasd:VirtualQuantity
/ovf:Itemovf:Itemrasd:AllocationUnitsbyte * 2^20/rasd:AllocationUnits
rasd:DescriptionMemory Size/rasd:Descriptionrasd:ElementName512 MB of memory/rasd:ElementNamerasd:InstanceID2/rasd:InstanceIDrasd:ResourceType4/rasd:ResourceTyperasd:VirtualQuantity512/rasd:VirtualQuantity/ovf:Item/ovf:VirtualHardwareSectiontrue

RESPONSE:

< Error minorErrorCode ="BAD_REQUEST" message="Requête incorrecte - Unexpected JAXB Exception - cvc-complex-type.2.4.a: Invalid content was found starting with element 'SourcedItem'. One of '{"http://www.vmware.com/vcloud/v1.5":IsSourceDelete, "http://www.vmware.com/vcloud/v1.5":SourcedVmInstantiationParams, "http://www.vmware.com/vcloud/v1.5":AllEULAsAccepted}' is expected." majorErrorCode="400" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://172.17.117.108/api/v1.5/schema/master.xsd" />

**Comment by lasko** [comment]
In my case the issue turns out that my vCloud Director is version 5.5 -- which does not seem to like the <SourcedItem> tag. The resolution to my problem was to check and see if the version matched 5.5, and if so to set SourcedItem = None.

I have implemented this into my version of pyvcloud and will submit the changes for merge.

**Comment by pacogomez** [comment]
thanks, send me the pull request and we'll review it and include it

**Comment by pacogomez** [comment]
fixed in current master, thanks
