### ISSUE TITLE
Python 3.6 and above required

### ISSUE THREAD

**Issue by cdivitotawela** [vmware/pyvcloud#438]
My understanding reading the README.md that pyvcloud module requires python3. At least I could not see any reference it says we require Python 3.6 or above. I struggled with following error before I realized that the syntax f"{href}/{domain.value}/{key}" is not valid for python 3.5. 

`File \"/venv/ansible/lib/python3.5/site-packages/pyvcloud/vcd/metadata.py\", line 207\n    f\"{href}/{domain.value}/{key}\"\n                                 ^\nSyntaxError: invalid syntax\n"`

Can update documentation (if it is not there already) indicating python 3.6 or above is required for the module please. I am happy to update the document and make a pull request if needed.

**Comment by pasikarkkainen** [comment]
I just noticed the same, python 3.4 didn't work, but vcd-cli (and pyvcloud) worked with python 3.6.

**Comment by shashim22** [comment]
Thank you for bringing it to our attention. README.md has now been updated to reflect required Python version correctly.

**Comment by cdivitotawela** [comment]
Thank you.

**Comment by carceneaux** [comment]
This issue looks to be complete and can be closed.
