### ISSUE TITLE
vCloud Organisation metadata support

### ISSUE THREAD

**Issue by chitashvili** [vmware/pyvcloud#474]
Hello community,

I have big needs to be able to inject metadata to Org/VDC. I was looking to example of VDC metadata and with same code I was able to reproduce it in Organization case. I have fork with that feature but sadly I am not good enough as python developer. I will highly appreciate if someone can review it and give some advice or guidance or use it as source for proper PR.

refer to: https://github.com/chitashvili/pyvcloud/commit/d95aaa33bd702aec242159eed70ac3dce30979d2

Thank you

**Comment by chitashvili** [comment]
As a reference added PULL request:
https://github.com/vmware/pyvcloud/pull/475

**Comment by pandeys** [comment]
Will follow up review in pull request #475 to check-in the code. Closing the thread.
