### ISSUE TITLE
connect_vms() not checking existing index

### ISSUE THREAD

**Issue by libowen9003** [vmware/pyvcloud#48]
I have 10 vnics in my template, so when I created the vapp, I used disconnect_from_networks() to remove all the vnics. After that I found that connect_vms() won't work, complaining that:

```
<Error xmlns="http://www.vmware.com/vcloud/v1.5" majorErrorCode="400" message="[ d0aae1fa-fef9-42ec-9b92-c4483b4c9552 ] The maximum number of NICs supported for this virtual machine with hardware version 8 is 10." minorErrorCode="BAD_REQUEST" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://us-virginia-1-4.vchs.vmware.com/api/compute/api/v1.5/schema/master.xsd"></Error>
```

Then I checked the request that connect_vms() made, I found two NetworkConnectionIndex set to 0:
`
send: 'PUT /api/compute/api/vApp/vm-a5f43a18-d062-4b0d-b215-f1581ccff807/networkConnectionSection/ HTTP/1.1\r\nHost: us-virginia-1-4.vchs.vmware.com\r\nContent-Length: 4080\r\nAccept-Encoding: gzip, deflate\r\nx-vcloud-authorization: 97db3b170a054069807ce6b019413342\r\nAccept: application/*+xml;version=5.7\r\nUser-Agent: python-requests/2.4.3 CPython/2.7.6 Linux/3.13.0-29-generic\r\nConnection: keep-alive\r\n\r\n<vmw:NetworkConnectionSection xmlns="http://www.vmware.com/vcloud/v1.5" xmlns:vmw="http://www.vmware.com/vcloud/v1.5" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" xmlns:yyy1="http://schemas.dmtf.org/ovf/envelope/1" yyy1:required="false" href="https://us-virginia-1-4.vchs.vmware.com/api/compute/api/vApp/vm-a5f43a18-d062-4b0d-b215-f1581ccff807/networkConnectionSection/" type="application/vnd.vmware.vcloud.networkConnectionSection+xml"><ovf:Info xmlns:vmw="http://www.vmware.com/vcloud/v1.5" msgid="">Specifies the available VM network connections</ovf:Info><vmw:PrimaryNetworkConnectionIndex>0</vmw:PrimaryNetworkConnectionIndex><vmw:NetworkConnection needsCustomization="true" network="none"><vmw:NetworkConnectionIndex>0</vmw:NetworkConnectionIndex><vmw:IsConnected>false</vmw:IsConnected><vmw:MACAddress>00:50:56:36:52:94</vmw:MACAddress><vmw:IpAddressAllocationMode>NONE</vmw:IpAddressAllocationMode></vmw:NetworkConnection><vmw:NetworkConnection needsCustomization="true" network="none"><vmw:NetworkConnectionIndex>1</vmw:NetworkConnectionIndex><vmw:IsConnected>false</vmw:IsConnected><vmw:MACAddress>00:50:56:36:52:95</vmw:MACAddress><vmw:IpAddressAllocationMode>NONE</vmw:IpAddressAllocationMode></vmw:NetworkConnection><vmw:NetworkConnection needsCustomization="true" network="none"><vmw:NetworkConnectionIndex>2</vmw:NetworkConnectionIndex><vmw:IsConnected>false</vmw:IsConnected><vmw:MACAddress>00:50:56:36:52:96</vmw:MACAddress><vmw:IpAddressAllocationMode>NONE</vmw:IpAddressAllocationMode></vmw:NetworkConnection><vmw:NetworkConnection needsCustomization="true" network="none"><vmw:NetworkConnectionIndex>3</vmw:NetworkConnectionIndex><vmw:IsConnected>false</vmw:IsConnected><vmw:MACAddress>00:50:56:36:52:97</vmw:MACAddress><vmw:IpAddressAllocationMode>NONE</vmw:IpAddressAllocationMode></vmw:NetworkConnection><vmw:NetworkConnection needsCustomization="true" network="none"><vmw:NetworkConnectionIndex>4</vmw:NetworkConnectionIndex><vmw:IsConnected>false</vmw:IsConnected><vmw:MACAddress>00:50:56:36:52:98</vmw:MACAddress><vmw:IpAddressAllocationMode>NONE</vmw:IpAddressAllocationMode></vmw:NetworkConnection><vmw:NetworkConnection needsCustomization="true" network="none"><vmw:NetworkConnectionIndex>5</vmw:NetworkConnectionIndex><vmw:IsConnected>false</vmw:IsConnected><vmw:MACAddress>00:50:56:36:52:99</vmw:MACAddress><vmw:IpAddressAllocationMode>NONE</vmw:IpAddressAllocationMode></vmw:NetworkConnection><vmw:NetworkConnection needsCustomization="true" network="none"><vmw:NetworkConnectionIndex>6</vmw:NetworkConnectionIndex><vmw:IsConnected>false</vmw:IsConnected><vmw:MACAddress>00:50:56:36:52:9a</vmw:MACAddress><vmw:IpAddressAllocationMode>NONE</vmw:IpAddressAllocationMode></vmw:NetworkConnection><vmw:NetworkConnection needsCustomization="true" network="none"><vmw:NetworkConnectionIndex>7</vmw:NetworkConnectionIndex><vmw:IsConnected>false</vmw:IsConnected><vmw:MACAddress>00:50:56:36:52:9b</vmw:MACAddress><vmw:IpAddressAllocationMode>NONE</vmw:IpAddressAllocationMode></vmw:NetworkConnection><vmw:NetworkConnection needsCustomization="true" network="none"><vmw:NetworkConnectionIndex>8</vmw:NetworkConnectionIndex><vmw:IsConnected>false</vmw:IsConnected><vmw:MACAddress>00:50:56:36:52:9c</vmw:MACAddress><vmw:IpAddressAllocationMode>NONE</vmw:IpAddressAllocationMode></vmw:NetworkConnection><vmw:NetworkConnection needsCustomization="true" network="none"><vmw:NetworkConnectionIndex>9</vmw:NetworkConnectionIndex><vmw:IsConnected>false</vmw:IsConnected><vmw:MACAddress>00:50:56:36:52:9d</vmw:MACAddress><vmw:IpAddressAllocationMode>NONE</vmw:IpAddressAllocationMode></vmw:NetworkConnection><vmw:NetworkConnection network="data-1"><NetworkConnectionIndex>0</NetworkConnectionIndex><IsConnected>true</IsConnected><IpAddressAllocationMode>DHCP</IpAddressAllocationMode></vmw:NetworkConnection><vmw:Link href="https://us-virginia-1-4.vchs.vmware.com/api/compute/api/vApp/vm-a5f43a18-d062-4b0d-b215-f1581ccff807/networkConnectionSection/" type="application/vnd.vmware.vcloud.networkConnectionSection+xml" rel="edit"/></vmw:NetworkConnectionSection>'
`
So do we want to check index before create a new NetworkConnection object?

Thansk,

**Comment by libowen9003** [comment]
If you don't mind 'disconnected' vnic being deleted, a possible solution for this is:
```
  def _modify_networkConnectionSection(self, section, new_connection,
                                       primary_index=None): 

      for networkConnection in section.get_NetworkConnection():
          if (networkConnection.get_network().lower() ==
              new_connection.get_network().lower()):
              return (False,
                      "VApp {0} is already connected to org vdc network {1}"
                      .format(self.name, networkConnection.get_network()))
+     found_disconnected = False
+     net_conns = section.get_NetworkConnection()
+     for index, net_conn in enumerate(net_conns):
+         if not net_conn.get_IsConnected():
+             net_conns[index] = new_connection
+             found_disconnected = True
+             break
+     if not found_disconnected:
~         section.add_NetworkConnection(new_connection)
      if section.get_Info() is None:
          info = vcloudType.Msg_Type()
          info.set_valueOf_("Network connection")
          section.set_Info(info)
      if primary_index is not None:
          section.set_PrimaryNetworkConnectionIndex(primary_index)
```

**Comment by hodgesrm** [comment]
Referenced code does not exist any more as far as I can tell. Closing as obsolete.
