### ISSUE TITLE
Create gateway IP configuration does not work

### ISSUE THREAD

**Issue by cdivitotawela** [vmware/pyvcloud#481]
When a edge gateway is created for vDC, we provide 
```python
is_ip_settings_configured = True
ext_net_to_participated_subnet_with_ip_settings = { 'test-external-network': { '10.9.10.1/24': '10.9.10.170' }}
```
I have noticed a bug where that it compares a string and int and IP is never configured. Problem is in function _create_gateway_configuration_param
```python
if subnet_arr[0] == ip_scope.Gateway.text and \
   subnet_arr[1] == prefix_len:
```
Here prefix_len is int value which is returned by function netmask_to_cidr_prefix_len. On subnet_arr[1] which is the value 24 is string. This values is derived from the variable ext_net_to_participated_subnet_with_ip_settings splitting 10.9.10.1/24'. So its comparing str and int which will never match so no ip configure ever.

**Comment by rajeshk2013** [comment]
Let me take a look. I will fix it. Thanks.

**Comment by cdivitotawela** [comment]
This has been fixed, approved and merged. Thanks @rajeshk2013 for quick review of the change.
