### ISSUE TITLE
Can I set or modify Org lease policies?

### ISSUE THREAD

**Issue by Cylindric** [vmware/pyvcloud#512]
I am using  pyvcloud to deploy various resources to vCD, and can't seem to find a way to set the lease policies on an Org. I'm talking about the settings in the Organization Properties window under "Policies"/"Leases".

I can't find any reference to `lease` in org.py, system.py or anywhere else really. Currently new Orgs are just adopting a default 7 day lease.

**Comment by chitashvili** [comment]
Hello, currently there is no such functionality. It is one pull request which lets you define them during create org. #406 but is is not merged yet.

**Comment by cdivitotawela** [comment]
@Cylindric As @chitashvili said you may be able to use the code in #406 

Only owners of the repository can approve and merge the PRs. So we have to wait one of the owners either merge or provide more information how we can get this merged.

I use ansible and currently I create my own classes extending the original Org class and implement new features.

**Comment by pandeys** [comment]
It is in our backlog and we will work on it.

**Comment by dev-dom** [comment]
Also merge https://github.com/vmware/pyvcloud/pull/593 takes care of ldap, saml, leases and all extended settings used in the org creation.
Best Regards,
Domenico

**Comment by Harish0596** [comment]
Is this feature released ?, right now when I create an organization it is getting created as per the VCDs default lease policies, but I want to set a different one
