### ISSUE TITLE
Add a method to modify a VDC

### ISSUE THREAD

**Issue by surfer190** [vmware/pyvcloud#515]
As of 20.1.0, there is no method to modify an existing VDC.

Add a method to modify a VDC, you can read the information about the [API call to modify a VDC](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/f27d65ea-c25b-45ed-9193-c8cc77507622/9a1f04e3-359b-4a19-9c62-7c0fafdfeac8/doc/doc/types/AdminVdcType.html)

**Comment by pandeys** [comment]
We will take this feature in our backlog.

**Comment by azzamsa** [comment]
any update about this?
