### ISSUE TITLE
Qestion: why there's no create_gateway function available for api prior than 30?

### ISSUE THREAD

**Issue by carmineesposito73** [vmware/pyvcloud#518]
I'm using vcloud with api 27.0 and https://github.com/vmware/ansible-module-vcloud-director  to create a gateway edge. The module vcd_vdc_gateway.py call the function vdc.create_gateway that is no more available in 20.1.0
```
grep "def create_gateway" /usr/local/lib/python3.6/dist-packages/pyvcloud/vcd/vdc.py
    def create_gateway_api_version_32(
    def create_gateway_api_version_30(
    def create_gateway_api_version_31(
```
while it was in 20.0.1 present in version 20.0.1
```
grep "def create_gateway" vcd/vdc.py 
    def create_gateway(
    def create_gateway_api_version_30(
```
does it mean that the api 27.0 is no more supported?

**Comment by rajeshk2013** [comment]
For API version 27.0, you should be using create_gateway_api_version_30. We should update the function name.

if float(api_version) <= float(ApiVersion.VERSION_30.value):
            result = vdc.create_gateway_api_version_30(
                name, external_networks_name, gateway_config, description,
                is_configured_default_gw, default_gateway_external_network,
                default_gw_ip, is_dns_relay, is_ha, is_advanced,
                is_distributed_routing, is_ip_settings_configured,
                ext_net_to_participated_subnet_with_ip_settings,
                is_sub_allocate_ip_pools_enabled,
                ext_net_to_subnet_with_ip_range, ext_net_to_rate_limit)

**Comment by carmineesposito73** [comment]
actually the ` create_gateway_api_version_30` doesn't work with API 27.0
```
 "msg": "Status code: 400/BAD_REQUEST, Bad request  - Unexpected JAXB Exception  - cvc-complex-type.2.4.d: Invalid content was found starting with element 'DistributedRoutingEnabled'. No child element is expected at this point. (request id: 7926703a-eb1b-4513-b3ac-d2d7c250ec99)"
```
to go further I've to make some changes:
```
$ git diff
diff --git a/pyvcloud/vcd/vdc.py b/pyvcloud/vcd/vdc.py
index c18e516..f2c4d65 100644
--- a/pyvcloud/vcd/vdc.py
+++ b/pyvcloud/vcd/vdc.py
@@ -1943,8 +1943,8 @@ class VDC(object):
         gateway_configuration_param.append(syslog_server_settings)
         gateway_configuration_param.append(
             E.AdvancedNetworkingEnabled(should_create_as_advanced))
-        gateway_configuration_param.append(
-            E.DistributedRoutingEnabled(is_dr_enabled))
+        # gateway_configuration_param.append(
+        #    E.DistributedRoutingEnabled(is_dr_enabled))
         return gateway_configuration_param
 
     def delete_gateway(self, name):
```
now I'm able to create the edge, but there are some errors (I need further investigation)

**Comment by pandeys** [comment]
We will take it in our backlog and create separate method for api 27.0

**Comment by carmineesposito73** [comment]
you closed this issue, but I cannot see the method for api 27.0

**Comment by pandeys** [comment]
API 27.0 is out of support from VCD, so we will not implement it.
