### ISSUE TITLE
vApp retrieve attached disks example

### ISSUE THREAD

**Issue by pimuzzo** [vmware/pyvcloud#537]
I am searching for a way to retrieve all disks attached to a vApp or a Vm.
At the moment I'm tring to achieve the result with `get_linked_resource` method without success.
I've seen that from a disk is possible to retrieve the attached vm with: `self.client.get_linked_resource(disk, RelationType.DOWN, EntityType.VMS.value)` I need a similar thing but in input I've got only the vApp or the Vm.
For each disk I need the id in the "uuid" form.

**Comment by kkkothari** [comment]
Hi @pimuzzo,
you iterate VM or Vapp object and get the vapp.resource.VmSpecSection.DiskSection and get all disk.
For all disk together there have no URL from API of VCD.
