### ISSUE TITLE
Issues with connecting VMs

### ISSUE THREAD

**Issue by lasko** [vmware/pyvcloud#54]
Currently I have to create a vapp via:
```
vca.create_vapp(self.vdc_name, self.vapp_name, "mytemplate", "mycatalog")
```
A Vapp is created and a VM is created. The problem I'm having is related to connecting the Vapp/VM to my Org Network. Defining it in the create_vapp fails and my "workaround" is as follows:

- Create the Vapp via the create_vapp function 
- Login to a browser and disconnect/delete the NIC that the VM has.
- Then run another script to that does the following:
```
        task = the_vapp.disconnect_from_networks()
        result = vca.block_until_completed(task)
        task = the_vapp.connect_to_network(nets[0].name, nets[0].href)
        result = vca.block_until_completed(task)
        # Connect the VMS to the network
        task = the_vapp.connect_vms(nets[0].name, connection_index=0, ip_allocation_mode="POOL")
        result = vca.block_until_completed(task)
```
I can then see that the vApp is connected to the Proper OrgNetwork, and the VM is also on the right network.

Help?

**Comment by lasko** [comment]
I suppose one way to do this would be to implement a function that would delete the VM NIC for me, but I'd like to figure out a better way to handle this.

**Comment by lasko** [comment]
After the recent updates and merges I've had success in getting this to work on vCloud Director API version 5.5

```
            running = self.vca.create_vapp(self.vdc_name, self.vapp_name, "mytemplate", "mycatalog", vm_name=myname)
            result = self.vca.block_until_completed(running)
            the_vdc = self.vca.get_vdc(self.vdc_name)
            the_vapp = self.vca.get_vapp(the_vdc, myvappname)
            nets = filter(lambda n: n.name == "Production_LAN", self.vca.get_networks(myvdcname))
            task = the_vapp.connect_vms(nets[0].name, connection_index=0, ip_allocation_mode="POOL")
            result = self.vca.block_until_completed(task)
```

The issue was with trying to use disconnect_from_networks() and connect_to_network()
completely by passing those methods seems to be the solution for my problem.

**Comment by pacogomez** [comment]
good to know, thanks
