### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by manuelmazzuola** [vmware/pyvcloud#540]
I was wondering if this project is dead because there are a lot of PRs not yet merged, but essentials, some have been open for a long time.

**Comment by johnnycuse** [comment]
Not dead, the team will be working to merge the PR's shortly.

**Comment by kkkothari** [comment]
@manuelmazzuola which issue are you talking. can you please provide link for that so team can look into that

**Comment by pandeys** [comment]
No response from author. Closing the thread.
