### ISSUE TITLE
Error when looking for vApptemplate.

### ISSUE THREAD

**Issue by btalebali** [vmware/pyvcloud#57]
Hello,
I tries to get all available vApptemplate form my vDC's catalogue, I used "get_vdc_templates" But always I have an error:

> > > y=vca._get_vdc_templates()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/pyvcloud/vcloudair.py", line 318, in _get_vdc_templates
> > >     self.response = requests.get(link[0].get_href(), headers=self.vcloud_session.get_vcloud_headers(), verify=self.verify)
> > > IndexError: list index out of range

Many thanks,
Bechir

**Comment by hodgesrm** [comment]
Please retry with current version of pyvcloud.  Closing as obsolete.
