### ISSUE TITLE
Upload an iso media to a catalog

### ISSUE THREAD

**Issue by piraz** [vmware/pyvcloud#58]
I want the ability of upload an iso media to the catalog.

The api will receive the catalog name, media name, description and type and the path to the iso file.

I don't know if media type is necessary on this case but at the HTTP Api it looks like other types of media can be uploaded but by default the ISO media type is used.

**Comment by piraz** [comment]
When we start to put the file to the catalog it would be great to send it in chunks because ISO files can be really big. I've looked the API and it seems to support this feature.

**Comment by pacogomez** [comment]
This is already in the master branch and will be released in version 13
