### ISSUE TITLE
issue with getting CPU and MEM

### ISSUE THREAD

**Issue by 387119** [vmware/pyvcloud#589]
reference issue https://github.com/vmware/pyvcloud/issues/463 closed without fixing

creating new issue for the same

vCloud Director version: 8.20.0.6875354
doc: https://vmware.github.io/pyvcloud/pyvcloud.vcd.vm.html

example:
vm = VM(client, resource=vm_resource)
vm_mem=vm.get_memory()

Traceback (most recent call last):
File "list-vcloud-all-resources.py", line 147, in 
vm_mem=vm.get_memory()
File "/opt/vcloud/pyvcloud/vcd/vm.py", line 111, in get_memory
self.resource.VmSpecSection.MemoryResourceMb.Configured.text)
File "src/lxml/objectify.pyx", line 231, in lxml.objectify.ObjectifiedElement.getattr
File "src/lxml/objectify.pyx", line 451, in lxml.objectify._lookupChildOrRaise
AttributeError: no such child: {http://www.vmware.com/vcloud/v1.5}VmSpecSection

vm_cpu=vm.get_cpus()

Traceback (most recent call last):
File "list-vcloud-all-resources.py", line 147, in 
vm_cpus=vm.get_cpus()
File "/opt/vcloud/pyvcloud/vcd/vm.py", line 97, in get_cpus
int(self.resource.VmSpecSection.NumCpus.text),
File "src/lxml/objectify.pyx", line 231, in lxml.objectify.ObjectifiedElement.getattr
File "src/lxml/objectify.pyx", line 451, in lxml.objectify._lookupChildOrRaise
AttributeError: no such child: {http://www.vmware.com/vcloud/v1.5}VmSpecSection

for example other commands:
get_power_state & get_resources - work with no issues

state=vm.get_power_state()
print (state)
result: 4

**Comment by kkkothari** [comment]
Pysdk support API Version 29.0(Minimum). 
Are you facing issue in  API Version 29 or higher ?

**Comment by pandeys** [comment]
VCD 8.20 API version is not supported. Are you facing issue in supported VCD version? Could you please check VM API body. I looked it as:
<VmSpecSection>
        <ovf:Info>Virtual hardware requirements (simplified)</ovf:Info>
        <OsType>windows9Server64Guest</OsType>
        <NumCpus>1</NumCpus>
        <NumCoresPerSocket>1</NumCoresPerSocket>
        <CpuResourceMhz>
            <Configured>1</Configured>
            <Reservation>200</Reservation>
            <Limit>1000</Limit>
            <SharesLevel>NORMAL</SharesLevel>
            <Shares>1000</Shares>
        </CpuResourceMhz>
        <MemoryResourceMb>
            <Configured>4</Configured>
            <Limit>4</Limit>
            <SharesLevel>NORMAL</SharesLevel>
            <Shares>40</Shares>
        </MemoryResourceMb>

and given logic is providing data in a dict.

**Comment by 387119** [comment]
nope, my api version is 

https://<IP>/api/versions
<VersionInfo deprecated="false">
<Version>26.0</Version>

**Comment by kkkothari** [comment]
Please upgrade vcd.

**Comment by 387119** [comment]
understand, thanks
