### ISSUE TITLE
Version issues with 5.5 and older

### ISSUE THREAD

**Issue by lasko** [vmware/pyvcloud#62]
The latest release of the code creates the same issues as #41 as a result of the fix in #61 

The fix should have been something like this:
```
+
+        if vm_name or vm_cpus or vm_memory:
+            params = vcloudType.SourcedCompositionItemParamType()
+            if ((self.version == "1.0") or (self.version == "1.5") 
+                    or (self.version == "5.1") or (self.version == "5.5")):
+                pass
+            else:
```

I'll put in a pull request for this but I'm not sure how this affects vca-cli as I'm not using it in my environment.

**Comment by pacogomez** [comment]
fixed in current master, thanks for reporting
