### ISSUE TITLE
Bug in get_vdc and get_gateway

### ISSUE THREAD

**Issue by Harish0596** [vmware/pyvcloud#632]
If the vdc is not present in under the Organization instead of raising EntityNotFoundException, it is returning none.

    def get_vdc(self, name, is_admin_operation=False):
        """Retrieves resource of an org vdc identified by its name.

        :param str name: name of the org vdc to be retrieved.

        :param bool is_admin_operation: if set True, will return the admin
            view of the org vdc resource.

        :return: an object containing EtityType.VDC XML data representing the
            vdc.

        :rtype: lxml.objectify.ObjectifiedElement

        :raises: EntityNotFoundException: if the named vdc can not be found.
        """
        if self.resource is None:
            self.reload()
        if self.client.get_api_version() < ApiVersion.VERSION_33.value:
            links = get_links(
                self.resource,
                rel=RelationType.DOWN,
                media_type=EntityType.VDC.value)
        else:
            links = self.client.get_resource_link_from_query_object(
                self.resource, media_type=EntityType.RECORDS.value, type='vdc')
        for link in links:
            if name == link.name:
                if is_admin_operation:
                    href = get_admin_href(link.href)
                else:
                    href = get_non_admin_href(link.href)
                return self.client.get_resource(href)
        return None

instead of returning None we can return as follows
raise EntityNotFoundException('org vdc \'%s\' not found' % name)

and the same goes for get_gateway also

    def get_gateway(self, name):
        """Get a gateway in the current org vdc.

        :param str name: name of the gateway to be fetched.

        :return: gateway

        :rtype: lxml.objectify.ObjectifiedElement

        :raises: EntityNotFoundException: if the named gateway can not be
        found.
        :raises: MultipleRecordsException: if more than one gateway with the
            provided name are found.
        """
        name_filter = ('name', name)
        query = self.client.get_typed_query(
            ResourceType.EDGE_GATEWAY.value,
            query_result_format=QueryResultFormat.RECORDS,
            equality_filter=name_filter)
        records = list(query.execute())
        if records is None or len(records) == 0:
            return None
        elif len(records) > 1:
            raise MultipleRecordsException("Found multiple gateway named "
                                           "'%s'," % name)
        return records[0]

**Comment by Harish0596** [comment]
Does this issue fixed ?

**Comment by shashim22** [comment]
There is no active development in pyvcloud now. We won't fix it. However, if contributors submit pull requests, the team will review them and merge them into the master branch.
