### ISSUE TITLE
Bug in _create_instantiateVAppTemplateParams

### ISSUE THREAD

**Issue by ncantor** [vmware/pyvcloud#64]
When creating a new machine, _create_instantiateVAppTemplateParams attempts to pass a set of parameters to the templateParameters, using add_SourcedItem. Unfortunately, add_SourcedItem isn't supported in versions older than 5.6, so the whole operation fails.
The snippet below is where things break, on the line
**templateParams.add_SourcedItem(params)**

```python
if ((self.version == "1.0") or (self.version == "1.5") or
           (self.version == "5.1") or (self.version == "5.5")):
            if vm_name or vm_cpus or vm_memory:
                params = vcloudType.SourcedVmInstantiationParamsType()
                params.set_Source(vcloudType.ReferenceType(href=vm_href))
                templateParams.add_SourcedItem(params)
                if vm_name:
                    pass```

**Comment by lasko** [comment]
See bug #62

**Comment by pacogomez** [comment]
fixed in current master
