### ISSUE TITLE
Any new versions?

### ISSUE THREAD

**Issue by ihumster** [vmware/pyvcloud#640]
21.0 was released in September 2019. Already released vCD 10. Many methods for the provider and not implemented. Project abandoned or frozen?

**Comment by nicslatts** [comment]
Hi @ihumster, we are working on a new python client that will be uploaded to pyvcloud in the coming months. The outcome of this work will be full vCD API coverage, with a consistent experience across the vCD Cloud API and legacy API. Regarding the existing client - the team has been focused on building the new client, but are still merging pull requests for the existing client.

**Comment by dwettstein** [comment]
Hi @shashim22 

What is about this topic? Will VMware release a new version of this SDK?

Thanks and kind regards!

**Comment by dwettstein** [comment]
https://github.com/vmware/pyvcloud/releases/tag/23.0.0 was released 🍾 🎉 
IMHO, this issue could be closed...
