### ISSUE TITLE
Not able to add a new disk to a VM

### ISSUE THREAD

**Issue by mukultaneja** [vmware/pyvcloud#647]
Description: While trying to add a new disk to a VM, method `add_disk_to_vm` is throwing `BadRequestException`

Please find attached a screenshot for more reference.

![Screenshot 2020-03-04 at 12 21 48 PM](https://user-images.githubusercontent.com/16931639/77576995-161c7880-6efc-11ea-8e2b-7f439c9f3f66.png)

**Comment by shashim22** [comment]
Mukul, thanks for fixing this.
