### ISSUE TITLE
how to update guest properties for a vm in vapp?

### ISSUE THREAD

**Issue by jdilipan** [vmware/pyvcloud#650]
I tried the following way to update the guest properties for a VM in vapp.

`result = vapp.update_product_section(key='AVICNTLR', value='10.79.204.23', user_configurable=True)
`
however, ovf properties reflected in the vm is as below.

`
AVICNTRL: 0.0.0.0, AVICNTRL.test-se-1: 10.79.204.23
`

Here - Expected is AVICNTRL is expected to have the ip address, but not seen. instead it is populated in AVICNTRL.test-se-1..here test-se-1 is the instance name.

The same is working if VM is created using Terraform. Can you let me know what is wrong here?

**Comment by shashim22** [comment]
The method to update guest properties of a VM hasn't been implemented. 

-Shashi
