### ISSUE TITLE
get_all_vms return empty list

### ISSUE THREAD

**Issue by Bronco97421** [vmware/pyvcloud#653]
Hello,

When I use this bloc of code, it's returning me nothing :

`for vdc,vapps in vApp_list.items():
    for vapp in vapps:
        vdc_obj = VDC(client, resource=org.get_vdc(vdc))
#        print(vdc_obj)
        print(vapp['name'])
        vapp_obj = VApp(client, resource=vdc_obj.get_vapp(vapp['name']))
        print(vapp_obj.get_all_vms())
`

I tried with get_vm() and specifying the name of the VM and it stills empty. But if I insert a wrong vm name, I get an error. Is there a way to get the list of vm that I don't know ?

I got the same behavior for get_resource.

Thanks by advance

**Comment by shashim22** [comment]
Hi,

Apologies for delay in response.

Mentioned block of code is working for me. 
Could you please look at the log to see if there is any exception? If yes, please paste the error stack trace.

-Shashi

**Comment by Bronco97421** [comment]
Hello,

It's okay, I used another method. I think it was the vcloud director provider.

I close this subject ! Thanks !

**Comment by cnolick** [comment]
@Bronco97421 Hi, how you got list all vm? I try this method and was receive only one vm :(
