### ISSUE TITLE
Timeout issues with block_until_completed function

### ISSUE THREAD

**Issue by lasko** [vmware/pyvcloud#66]
This is a recent issue but hopefully someone will have some insight
Occasionally when creating a vapp I'll receive a "Connection Refused" error from https://us-california-1-3.vchs.vmware.com --- When I turn on logging it looks like the HTTP session just times out while waiting for a task to finish.

Its pretty random on when it occurs during the creation of the vapp (using the create_vapp function). 
Its taking place during the block_until_completed() function.
As an example here is some (sterilized) log output showing whats happening:

```
send: 'GET /api/compute/api/task/xxxxxxxxxxxxxxxxxxx HTTP/1.1\r\nHost: us-california-1-3.vchs.vmware.com\r\nConnection: keep-alive\r\nx-vcloud-authorization: xxxxxxxxxxxxxx\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/*+xml;version=5.7\r\nUser-Agent: python-requests/2.7.0 CPython/2.7.6 Linux/3.16.0-30-generic\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 01 Jul 2015 18:48:00 GMT
header: X-Frame-Options: SAMEORIGIN
header: X-VMWARE-VCLOUD-REQUEST-ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
header: x-vcloud-authorization: xxxxxxxxxxxxxxxxxxxxxx
header: X-VMWARE-VCLOUD-REQUEST-EXECUTION-TIME: 38
header: Content-Type: application/vnd.vmware.vcloud.task+xml;version=5.7
header: Content-Encoding: gzip
header: Vary: Accept-Encoding,User-Agent
header: Content-Length: 647
header: Via: 1.1 us-california-1-3.vchs.vmware.com
header: Keep-Alive: timeout=15, max=100
header: Connection: Keep-Alive
('Connection aborted.', error(111, 'Connection refused'))
```

I used a try/except statement on the vapp_create function and "('Connection aborted.', error(111, 'Connection refused'))"  is the Exception caught and printed.

Thoughts? This is a really big issue for me at the moment, and ultimately may end with me having to submit a ticket with the i am.vchs.vmware.com VMWare vCloud Air service to figure out why they are responding with "Connection Refused" or changing providers.

I have two cloud service providers, the other one does not have this issue and works flawlessly with my vapp creation script --

Help? Thoughts?

**Comment by hodgesrm** [comment]
vCloud Air is no longer supported.  Closing as obsolete.
