### ISSUE TITLE
get_catalog() func failed with Catalog not found error

### ISSUE THREAD

**Issue by gugansankar** [vmware/pyvcloud#669]
Hey,

We're using vCD infra that has around 100 catalogs in it. When I tested the list_catalogs() func, it's able to list all 100 catalogs.

But If I'm trying to get a particular catalog info using get_catalog() func, it's failed with 'catalog not found' error. I checked the pyvcloud.log, It’s trying to find the catalog only from the first 25 items [the RestAPI url it uses is paginated]. Seems it does not loop through all the items.

Error:

`Traceback (most recent call last):
  File "/Users/gkulandaivel/code/SonarPOC/sonarPoc/test.py", line 84, in <module>
    template = org.get_catalog('VAPP_DEPLOY', is_admin_operation=True)
  File "/Users/gkulandaivel/code/SonarPOC/.venv/lib/python3.7/site-packages/pyvcloud/vcd/org.py", line 213, in get_catalog
    raise EntityNotFoundException('Catalog not found (or)'
pyvcloud.vcd.exceptions.EntityNotFoundException: Catalog not found (or) Access to resource is forbidden`

**Comment by shashim22** [comment]
This is fixed in this pull request:
https://github.com/vmware/pyvcloud/pull/670
