### ISSUE TITLE
Errors in automatic generated files

### ISSUE THREAD

**Issue by kostya13** [vmware/pyvcloud#68]
In several files in dir  pyvcloud/schema/vcd/v1_5/schemas/vcloud (for example networkType.py)
I found error in GDSClassesMapping dictonary.
The node's root tag name and corresponding class are swapped.
I found two mismatches:
'AllocatedIpAddresses': IpAddressesType
'IpAddress': AllocatedIpAddressType
Therefore if I try parse string with root node AllocatedIpAddresses, the parser try use build function from IpAddressesType class.

**Comment by denismakogon** [comment]
@kostya13 fix proposed, https://github.com/vmware/pyvcloud/pull/80

**Comment by hodgesrm** [comment]
These files no longer exist.  Closing as obsolete.
