### ISSUE TITLE
[Help] Can't disable logging

### ISSUE THREAD

**Issue by azzamsa** [vmware/pyvcloud#680]
I've disabled all logging option, But I still have `vcd_pysdk.log`.

MWE

```python
client = ApiClient(
            host,
            api_version=api_version,
            verify_ssl_certs=verify_ssl,
            log_file=None,
            log_requests=False,  ## <<------ DISABLED
            log_headers=False,  ## <<------ DISABLED
            log_bodies=False,  ## <<------ DISABLED
        )
        # pyvcloud logging can't be disabled by default
        # log file will clutter docker image
        # we've our own log
        client._loggger = None   ## <<------ other trick, doesn't work
        client._get_default_loggger = None

        creds = BasicLoginCredentials(user, org, passwd)
        client.set_credentials(creds)
```

But still produced `vcd_pysdk.log`:

```text
API version in use: 33.0
API version in use: 33.0
API version in use: 33.0
API version in use: 33.0
API version in use: 33.0
API version in use: 33.0
API version in use: 33.0
API version in use: 33.0
API version in use: 33.0
API version in use: 33.0
API version in use: 33.0
API version in use: 33.0
API version in use: 33.0
API version in use: 33.0
...
```

I don't need this info. This will clutter my images.

Thank you.

**Comment by shashim22** [comment]
You can't disable pyvcloud log completely. Even if you pass log_file as None, it gets created using default name. If log is completely disabled, how to do you expect to print error messages in case of error conditions?

**Comment by azzamsa** [comment]
Logs from pycloud are raised, the caller can catch that error then collect it.

If I have flask app that use pyvcloud as dependency, I can wrap pyvcloud statement with try-except then get the error in except block. then feed it to stdout, collected by other external app (in distributed fashion).

So that I don't need pyvcloud to write error to file at all.

**Comment by azzamsa** [comment]
However, with the code below. the file only created, but doesn't contains anything. I am ok with it.

```    python
        client._loggger = None
        client._get_default_loggger = None
        import logging
        client._logger.setLevel(logging.CRITICAL)
        
```
