### ISSUE TITLE
Error 400 occurs when instantiating vApp from template with internal vApp network

### ISSUE THREAD

**Issue by Ptomerty** [vmware/pyvcloud#682]
Following up from https://github.com/vmware/vcd-cli/issues/534 since I read the source code and all roads led to [`instantiate_vapp()`](https://github.com/vmware/pyvcloud/blob/master/pyvcloud/vcd/vdc.py#L183).

Is there any way to instantiate a vApp (in this case, with multiple VMs) that already has an internal vApp network? Currently, the network settings default to looking for this network in the list of VDC networks, but the template has a vApp network, so obviously it won't be found. Thanks!

EDIT: It seems the error is that a template vApp network is incorrectly treated as a VDC network. Submitting PR to fix this issue.

**Comment by junankar** [comment]
@Ptomerty I was looking for exact same issue today! Thanks for submitting a fix.

**Comment by junankar** [comment]
I am also looking into creating vApp with just template information and vApp name (similar to webclient).

e.g.

<ns6:InstantiateVAppTemplateParams name="vAppName">
    <ns6:InstantiationParams/>
    <ns6:Source href="https://IP/api/vAppTemplate/vappTemplate-ID" id="urn:vcloud:vapptemplate:ID" name="vappTemplate-Name" type="application/vnd.vmware.vcloud.vAppTemplate+xml"/>
</ns6:InstantiateVAppTemplateParams>

Is there any way to skip specifying sourceitems ( SourcedItem  element of SourcedCompositionItemParamType)?

Following code is setting sourced_item:
vapp_template_params.append(sourced_item)

**Comment by Ptomerty** [comment]
You should create your own issue for that. As far as I can tell, though, that's not possible; the sourced_item object seems to be the actual VM before it's created.
