### ISSUE TITLE
Not able to add vm to existing vapp

### ISSUE THREAD

**Issue by priyaadhar** [vmware/pyvcloud#687]
Once a vapp is created, am trying to add vm's to it.

Tried with add_vms which is throwing error as it is not able to fnd source_vm
Tried with create_from_scratch which gives 500 internal server error

Please provide an alternative or  on how to resolve the iissue

**Comment by mukultaneja** [comment]
@priyaadhar could you please share error logs on the issue? vapp's `add_vms` method takes a `source_vm` to create `target_vm` inside a vapp. So it requires `source_vm` to be present or accessible to the user in a org.

**Comment by priyaadhar** [comment]
@mukultaneja I had created a vm in vapp "abc" and provided the same as source_vm to add_vms method, and got error "Cannot find Vm "abc"".
Then tried with other vm name and got the same error **Cannot find vm "abc"**.
And the vm is accessible to user in org

**Comment by mukultaneja** [comment]
ok. I assume this [line](https://github.com/vmware/pyvcloud/blob/master/pyvcloud/vcd/vapp.py#L911) could throw the same error. Could you please share the arguments which you are passing to `add_vms` method? If the source VM is accessible and part of the vApp then it should work.

**Comment by priyaadhar** [comment]
@mukultaneja  Yes the line you mentioned is throwing the error. 
**Arguments for add_vms** 
      catalog_item = self.org.get_catalog_item(catalog,"Ubuntu-1204")
      source_vapp_resource = self.client.get_resource(
                            catalog_item.Entity.get('href'))
       spec = {'source_vm_name': "sample_vapp1",'vapp': source_vapp_resource}
        spec['target_vm_name'] = hostname
        spec['hostname'] = hostname
        spec['network'] = network
        spec['ip_allocation_mode'] = ip_allocation
        spec['storage_profile'] = "*(Any)"
        vms = [spec]
        result = self.vapp.add_vms(vms, all_eulas_accepted=True)

In the line you have mentioned, it is printing the vm's in the Vapp and initially i had used that as source vm and tried to create vm. Even after that it was throwing error.

**Comment by mukultaneja** [comment]
`add_vms` is the method to add new vms inside the existing vapp. You can call `add_vms` method onto the target vapp where you want to add new vms. Now as from your arguments, I could see you are taking vm from a catalog so make sure `source_vm_name` should be exactly matched with the vm name present under `Ubuntu-1204` template. Apart from this, `storage_profile` should be a `href` instead of a `name string`.

**Comment by priyaadhar** [comment]
@mukultaneja Thanks for the pointer, passing href to storage profile resolved the issue
