### ISSUE TITLE
vapp add_disk_to_vm fails due to vapp get_all_vms returning empty

### ISSUE THREAD

**Issue by DanielFarrarCO** [vmware/pyvcloud#700]
Hello!  I've ran into an issue with a few modules inside of vapp.py and I'm unsure if it's my setup or a bug.  I'm trying to call:
vm_disk_resource = vapp.add_disk_to_vm(vm_name, disk_size)
But the request hangs indefinitely. I dug into the Python and added some debugs to find that "disk_list" is empty, because calling get_all_vms() is returning empty.  

**Setup:**

> CentOS8 container
> pyvcloud==22.0.1
> Python 3.6.8
> vCloud Director version: 9.7.0.14534864
> VCD API support /api/versions: 20.0 - 32.0

Here's the output of my debug, added [empty] where nothing is being returned:

get_vm vm_name:
NAME-VAPPTEST-L052

get_all_vms:
[empty]

vm_name:
NAME-VAPPTEST-L052

get_vm vm_name:
NAME-VAPPTEST-L052

get_all_vms:
[empty]

disk_list:
[empty]

new_disk:
[empty]

vm.get('href') + '/virtualHardwareSection/disks':
https://MYVCD.com/api/vApp/vm-redacted-UUID/virtualHardwareSection/disks

disk_list:
[empty]

EntityType.RASD_ITEMS_LIST.value:
application/vnd.vmware.vcloud.rasdItemsList+xml

vm.get('href') + '/virtualHardwareSection/disks', disk_list, EntityType.RASD_ITEMS_LIST.value:
https://MYVCD.com/api/vApp/vm-redacted-UUID/virtualHardwareSection/disks. 
 application/vnd.vmware.vcloud.rasdItemsList+xml

And here's the code snip from vapp.py for context:

>     def get_all_vms(self):
>         """Retrieve all the vms in the vApp.
> 
>         :return: a list of lxml.objectify.ObjectifiedElement objects, where
>             each object contains EntityType.VM XML data and represents one vm.
> 
>         :rtype: empty list or generator object
>         """
>         self.get_resource()
>         print("get_all_vms:")
>         print(self.get_resource())
>         if hasattr(self.resource, 'Children') and \
>                 hasattr(self.resource.Children, 'Vm') and \
>                 len(self.resource.Children.Vm) > 0:
>             return self.resource.Children.Vm
>         else:
>             return []
> 
>     def get_vm(self, vm_name):
>         """Retrieve the vm with the given name in this vApp.
> 
>         :param str vm_name: name of the vm to be retrieved.
> 
>         :return: an object contains EntityType.VM XML data that represents the
>             vm.
> 
>         :rtype: lxml.objectify.ObjectifiedElement
> 
>         :raises: EntityNotFoundException: if the named vm could not be found.
>         """
>         print("get_vm vm_name:")
>         print(vm_name)
>         for vm in self.get_all_vms():
>             if vm.get('name') == vm_name:
>                 return vm
>         raise EntityNotFoundException('Can\'t find VM \'%s\'' % vm_name)

I'm not sure where to go from here, any help or pointers would be greatly appreciated.  Thanks!

**Comment by mukultaneja** [comment]
@DanielFarrarCO, as per the code `get_vm()` should raise `EntityNotFoundException` even if `get_all_vms()` is returning an empty list. If you are not getting this exception, it means you are getting a VM object. 
And to another point, the current implementation requires at least 1 disk to be attached to the VM before adding a new disk. If you are able to get the proper output of `vm.get('href') + '/virtualHardwareSection/disks'` as you shared, then please try to add a disk manually before calling `add_disk_to_vm`.

**Comment by DanielFarrarCO** [comment]
Thank you for the notes!  I'll dig into this, the VM has Disk 0 (Bus 0, Unit 0) existing already and will verify output with your module shortly.  Would it make a difference if the VM hasn't been powered on yet?  Just came to my mind as I was typing this.

**Comment by mukultaneja** [comment]
No, it would not.

**Comment by DanielFarrarCO** [comment]
print(vm.general_setting_detail())
returns:
{'Name': 'NAME-VAPPTEST-L056', 'Computer Name': 'VAPPTEST-L056', 'OS Family': 'rhel7_64Guest', 'OS': 'Red Hat Enterprise Linux 7 (64-bit)', 'Boot Delay': 0, 'Enter BIOS Setup': False, 'Storage Policy': 'DEFAULT_STORAGE_POLICY'}

But I get this error from vm.get('href'), which I think may be pointing to my issue but I need to think about it.  Let me dig further.  Thanks again for your help!

print(vm.get('href') + '/virtualHardwareSection/disks')
AttributeError: 'VM' object has no attribute 'get'

**Comment by shashim22** [comment]
@DanielFarrarCO Are we good to close this?

**Comment by DanielFarrarCO** [comment]
I never figured this one out, but is still on my backlog of todo's for an automation project.  We can close and I'll reopen or comment if I find more details.
