### ISSUE TITLE
vCloudEntities.py invalid syntax in python3

### ISSUE THREAD

**Issue by dougmbaya** [vmware/pyvcloud#78]
Traceback (most recent call last):
....
....
    from pyvcloud.schema.vcd.v1_5.schemas.admin import vCloudEntities
  File "/Users/myfile/bin/pyvcloud/pyvcloud/schema/vcd/v1_5/schemas/admin/vCloudEntities.py", line 94
    except ImportError, exp:
                      ^
SyntaxError: invalid syntax

Using python3

**Comment by denismakogon** [comment]
@dougmbaya , fix was submitted https://github.com/vmware/pyvcloud/pull/79

**Comment by hodgesrm** [comment]
Python 3 is now fully supported.
