### ISSUE TITLE
Python 3 errors

### ISSUE THREAD

**Issue by vmbb** [vmware/pyvcloud#84]
The pip entry says it supports python 3, but I see print statements instead of functions in the code, and the **init**.py imports httplib instead of http.client.

From other issues, it seems folks are using it with python 3, but what is the trick? Do I need to use 2to3 and handle it myself?

Thanks!

**Comment by hodgesrm** [comment]
Python 3 is now fully supported and Python 2 is obsolete.  You should not see further problems.
