### ISSUE TITLE
Recent 15rc2 commit broke vcd support

### ISSUE THREAD

**Issue by ckamps** [vmware/pyvcloud#86]
Now login attempts alway result in unauthorized.  See comment on the [commit](https://github.com/vmware/pyvcloud/commit/213af8566de08b8859212a318837c01e6cce9411)

**Comment by jtyr** [comment]
This issue should be fixed by merging the PR #88.

**Comment by wyaeld** [comment]
@pacogomez are you still maintaining this?

**Comment by hodgesrm** [comment]
This is fixed; closing.
