### ISSUE TITLE
add_nat_rule ValueError

### ISSUE THREAD

**Issue by spopp** [vmware/pyvcloud#91]
Other nat rules worked but while trying to add nat rule:
{'TranslatedIp': '10.10.3.3', 'RuleType': 'DNAT', 'Enable': True, 'OriginalPort': 'any', 'TranslatedPort': 'any', 'OriginalIp': '215.216.66.240', 'Protocol': 'TCP', 'Id': 65552}

pyvcloud==15rc2
python2.7

pyvcloud/gateway.py tried to cast port 'any' to an int and failed with a ValueError.
at https://github.com/vmware/pyvcloud/blob/master/pyvcloud/gateway.py#L134

  File ".../.env/local/lib/python2.7/site-packages/pyvcloud/gateway.py", line 134, in add_nat_rule
    original_port_modified = str(int(original_port_modified) + 1)
ValueError: invalid literal for int() with base 10: 'any'

**Comment by mixmatch** [comment]
+1

**Comment by hodgesrm** [comment]
Appears to be fixed but we no longer support Python 2.x.  Closing.
