### ISSUE TITLE
Enumerate all vApps? get_vapps?

### ISSUE THREAD

**Issue by jblaine** [vmware/pyvcloud#97]
I've scoured the generated docs and poked around through the code but cannot find a way to collect a list of vApps to then iterate over. How might I do that?

The README does not list a contact address or mailing list, so I'm making this issue.

**Comment by mukultaneja** [comment]
H jblaine,

I think this [link](https://github.com/vmware/pyvcloud/blob/master/examples/list-vapps.py#L51) can help you to resolve your's issue.

**Comment by jblaine** [comment]
Thank you. That looks promising.

**Comment by jblaine** [comment]
Okay, that's progress, and 2 small PRs submitted too :) Am I similarly missing the clues about how to show VM properties (right now Operating System is my immediate need)? I've looked all through vm.py and friends in the last hour.

**Comment by dwettstein** [comment]
In my opinion, this issue could be closed, as it is implemented in vcd.py (https://github.com/vmware/pyvcloud/blob/b088b4cb8a97f99473ea500144110629dcf5ecbd/pyvcloud/vcd/vdc.py#L424).

**Comment by kkkothari** [comment]
list_vapp_details(self, resource_type, filter=None) in vdc.py help you
