### ISSUE TITLE
Cannot create disk of selected storage profile

### ISSUE THREAD

**Issue by kaneda-fr** [vmware/pyvcloud#99]
Hi,

The current version of pyvcloud doesn't allow to choose the storage profile when creating an independent disk (available through API since vCloud Director for service provider 5.6.3).

**Comment by kkkothari** [comment]
try VDC method create_disk(self,
                    name,
                    size,
                    bus_type=None,
                    bus_sub_type=None,
                    description=None,
                    storage_profile_name=None,
                    iops=None)
